- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/rero/ng-core/src/public-api.ts
* BETTER remove lazy loading in routing to avoid errors on chunk load in Invenio apps.
* BETTER export record components in public API.
Signed-off-by: Sébastien Délèze <sebastien.deleze@rero.ch>
> routing: record routing

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/ng-core-tester/src/app/app.component.html
- projects/ng-core-tester/src/app/app.component.ts
* Provides an example for how to use URLs matchers.
* Removes references to AlertComponent.
> routing: URL matcher example

- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Gets 1 record in API calls because 0 doesn't work after Invenio upgrade to 3.2.
> search: fix total counters

- .travis.yml
- projects/ng-core-tester/karma.conf.js
- projects/rero/ng-core/src/lib/record/editor/remote-input/remote-input.component.ts
- projects/rero/ng-core/src/lib/record/record.service.ts
- projects/rero/ng-core/src/lib/shared.module.ts
- projects/rero/ng-core/src/lib/validator/time.validator.ts
- projects/rero/ng-core/src/lib/validator/unique.validator.ts
- projects/rero/ng-core/src/public-api.ts
- run-tests.sh
* Adds new test script.
* Improves test by adding tester app into the tests.
* Adds new form validators: to test remotely the uniqueness of a value,
to check a range of time.
* Adds a function to clean a json before backend POST: remove empty
values.
* Improves the valueAlreadyExists function of the record-service to use
getRecords instead of a direct http call.
* Add variables to record-service for default and max number of results.
> many: backport some usefull functions

- projects/rero/ng-core/src/lib/api/api.service.ts
* Adds a method to get $ref endpoint for a given resource.
> api: get $ref endpoint

- package-lock.json
- package.json
- projects/ng-core-tester/src/app/app-config.service.ts
- projects/rero/ng-core/src/lib/api/api.service.ts
- projects/rero/ng-core/src/lib/core-config.service.ts
- projects/rero/ng-core/src/lib/record/record.service.ts
- run-tests.sh
* Adds a new method to the record service to get the schemaform endpoint.
* Adds a new property to the configuration object to store the
schemaform endpoint.
> record: add the schemaform endpoint to the config

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/ng-core-tester/src/app/record/document/detail/detail.component.html
- projects/ng-core-tester/src/app/record/document/document.component.html
- projects/ng-core-tester/src/app/record/document/document.component.ts
- projects/ng-core-tester/src/app/record/institution/institution.component.html
- projects/ng-core-tester/src/app/record/institution/institution.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- projects/rero/ng-core/src/lib/record/search/result/item/json.component.ts
- projects/rero/ng-core/src/lib/record/search/result/item/result-item.ts
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.html
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.ts
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.directive.ts
* Injects detail URL in directive which manage result item display.
* Provides example for displaying link to detail
* Corrects error on certain documents details in tester.
* Changes "patrons" key to "users" for displaying SONAR users in tester.
* Fixes issue #23
Co-Authored-by: Olivier Dossmann <git@dossmann.net>
> records: add link to detail on brief view title

- projects/rero/ng-core/src/lib/record/editor/add-reference/add-reference.component.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/submit/submit.component.html
- projects/rero/ng-core/src/lib/record/editor/submit/submit.component.spec.ts
- projects/rero/ng-core/src/lib/record/editor/submit/submit.component.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
* Disables submit button for invalid async validator: i.e. for item
barcode uniqueness validation.
* Removes useless debug traces.
* Uses core unique validator for remote input component.
> editor: fix submit button with async validator

- package.json
- projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
Changing the http query params update the search results.
* Adds a new alias for library build and pack -> `npm run pack`.
> search: fix url query params changes

- projects/rero/ng-core/src/public-api.ts
Enable bootstrap4framework export to allow other applications to create JSON Schema forms with our tools.
**This is needed by https://tree.taiga.io/project/rero21-reroils/task/1094**.
Co-Authored-by: Olivier DOSSMANN <git@dossmann.net>
> project: export custom bootstrap editor lib

- projects/rero/ng-core/src/lib/record/editor/fieldset/fieldset.component.ts
- projects/rero/ng-core/src/lib/record/editor/main-fields-manager/main-fields-manager.component.html
- projects/rero/ng-core/src/lib/record/editor/main-fields-manager/main-fields-manager.component.ts
* Enable/disable FormControl when a fieldset is show/hidden.
Co-Authored-by: Lauren-D <laurent.dubois@itld-solutions.be>
> editor: fix button validation

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/ng-core-tester/src/app/app.component.html
- projects/ng-core-tester/src/app/app.module.ts
- projects/ng-core-tester/src/app/home/home.component.ts
- projects/ng-core-tester/src/app/search-bar/search-bar.component.html
- projects/ng-core-tester/src/app/search-bar/search-bar.component.spec.ts
- projects/ng-core-tester/src/app/search-bar/search-bar.component.ts
- projects/rero/ng-core/src/lib/record/autocomplete/autocomplete.component.html
- projects/rero/ng-core/src/lib/record/autocomplete/autocomplete.component.spec.ts
- projects/rero/ng-core/src/lib/record/autocomplete/autocomplete.component.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
- projects/rero/ng-core/src/public-api.ts
- run-tests.sh
* Adds a new search input component with a remote autocomplete feature.
* Fixes patrons not found error on tester.
* Improves `run-tests.sh`: it failed in case of error.
Co-Authored-by: Sébastion Délèze <sebastien-deleze@rero.ch>
> autocomplete: add search input with autocompletion

- projects/rero/ng-core/src/lib/record/detail/detail.component.html
- projects/rero/ng-core/src/lib/record/detail/detail.component.ts
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.html
* Checks adminMode value in detail component for showing or hiding edition and deletion button.
* Floats right the buttons instead of using a grid column in brief view and detail view.
> resources: check adminMode value in detail component

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
* NEW Adds default PR and issue template.
To use same the templates than rero-ils (projects standardization)
N/A
> git: add PR and issue template

- projects/rero/ng-core/src/lib/pipe/get-record.pipe.spec.ts
- projects/rero/ng-core/src/lib/pipe/get-record.pipe.ts
- projects/rero/ng-core/src/lib/shared.module.ts
* Adds a new pipe to return a Record object given its pid and recordType.
* This pipe is able to return a specific field.
> pipe: create a new getRecord pipe

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/rero/ng-core/src/lib/record/detail/detail.component.ts
- projects/rero/ng-core/src/lib/record/record.service.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Adds a config to specify custom headers to api calls.
Co-Authored-by: Sébastion Délèze <sebastien-deleze@rero.ch>
> api: custom headers

- projects/rero/ng-core/src/lib/record/detail/detail.component.ts
- projects/rero/ng-core/src/lib/record/record-ui.service.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
- projects/rero/ng-core/src/lib/record/search/record-search-page.component.html
- projects/rero/ng-core/src/lib/record/search/record-search-page.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- projects/rero/ng-core/src/public-api.ts
* Splits RecordSearchComponent in two components, one for integration in template and one for routing.
* Moves check permissions to RecordUiService.
* Fixes #45.
Co-Authored-by: Sébastion Délèze <sebastien-deleze@rero.ch>
> records: search refactoring

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
* Checks permission to update the record in component init and redirects to previous page if user has no access.
* Fixes #39
> editor: check permission before showing the editor

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/rero/ng-core/src/lib/record/record-routing.module.ts
- projects/rero/ng-core/src/lib/record/search/record-search-page.component.html
- projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts
* Uses RecordSearchPageComponent for record routing.
* Lazy-loads routes from ng-core for records in ng-core-tester.
* Takes into account the adminMode parameter in RecordSearchComponent.
* Changes conditions for retrieving adminMode and showSearchInput parameters from data.
Co-Authored-by: Sébastien Délèze sebastien-deleze@rero.ch
> routing: fix routing issues

- projects/rero/ng-core/src/lib/core.module.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
* Configures ngx-translate to be used in a lazy loading module.
* Exports CoreModule in RecordModule.
- To fix the use of ng-core in a lazy loading module.
> module: fix translate module import for lazy loading

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.ts
- Fixes display more/less link if the parameter aggregationBucketSize isn't defined on data routing.
- Disabled parameter aggregationBucketSize on routing and show if the link "more" is not present.
> aggregation: Fix more/less link

- projects/rero/ng-core/src/lib/record/detail/detail.component.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- Fix redirection after add, update, delete resource
- Add, edit and update record and check the redirection
> general: fix redirection after add, update, delete resource

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
* Changes the URL after a submission but do not push it in the history.
- Go to an item_types list, create or update, submit, it is redirected to the detailed view, check the URL, push back. You are in the list again.
> editor: fixes editor redirection

- projects/rero/ng-core/src/lib/record/autocomplete/autocomplete.component.ts
* The input value is set only if the url q parameters is for the
autocomplete for example: records/documents.
- Fix an issue.
- Go to a page with two search inputs, try search in the search input in the page, the value of search input in the header should not be updated.
> autocomplete: fix multiple search input in a page

- projects/rero/ng-core/src/lib/record/search/record-search.component.html
* Decreases y-margins of search input section.
> search: decrease margins

- projects/ng-core-tester/src/app/app-config.service.ts
- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/ng-core-tester/src/app/app.component.ts
- projects/ng-core-tester/src/app/record/document/detail/detail.component.ts
- projects/ng-core-tester/src/app/record/document/document.component.html
- projects/ng-core-tester/src/app/record/document/document.component.ts
- projects/ng-core-tester/src/environments/environment.prod.ts
- projects/ng-core-tester/src/environments/environment.ts
- projects/rero/ng-core/src/lib/core-config.service.ts
- projects/rero/ng-core/src/lib/core.module.ts
- projects/rero/ng-core/src/lib/service/title-meta.service.spec.ts
- projects/rero/ng-core/src/lib/service/title-meta.service.ts
- projects/rero/ng-core/src/public-api.ts
* Adds service for title and meta html
* Adds new parameter prefixWidow on config
* Implements this service on ng-core-tester
- to add possibility to modify title and meta on head html
- Check title on tab
> service: add new service to personalized title and meta html

- projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Removes useless component RecordSearchPage.
* Refactors RecordSearchComponent.
* Unsubscribes from route observables on component destruction.
* Removes standalone RecordSearchComponent integration.
* Fixes #86.
> records: search refactor

- projects/rero/ng-core/src/lib/utils/utils.spec.ts
- projects/rero/ng-core/src/lib/utils/utils.ts
* Corrects method to get pid from $ref.
* Adds unit tests to check the method.
To correct the method for getting pid from $ref.
https://tree.taiga.io/project/rero21-reroils/task/1116?kanban-status=1224895
Tested with unit tests.
Is needed in https://github.com/rero/rero-ils-ui/pull/92
> fix: correct method to get pid from $ref

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
* Adds postprocessRecordEditor to update data after submit form.
* Adds preCreateRecord to update data before create record.
* Adds preUpdateRecord to update data before update record.
- add process data record
> editor: add process data record

- projects/rero/ng-core/src/lib/record/editor/type/datepicker-type.component.ts
* Fixes datepicker output date value.
* Adds new parameter "outputDateFormat" to template options.
- Fix output date format
> datepicker: fix output value

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/toggle-wrapper/toggle-wrappers.component.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
* Add a new 'toggle-switch' wrapper
- Allow to hide/view a set of fields using a switch button not defined into json schema
- use the https://github.com/rero/rero-ils/pull/708 from rero-ils (bootstrap / setup ?)
- Edit a location 
- The switch "restrict_pickup ?" allow to hide/view "locations URI" below
> editor: new wrapper toggle-switch

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/ng-core-tester/src/app/routes/documents-hevs-route.ts
- projects/ng-core-tester/src/app/routes/documents-route.ts
- projects/ng-core-tester/src/app/routes/route.service.ts
- projects/rero/ng-core/src/lib/route/route-collection.service.spec.ts
- projects/rero/ng-core/src/lib/route/route-collection.service.ts
- projects/rero/ng-core/src/lib/route/route-interface.ts
- projects/rero/ng-core/src/public-api.ts
* Adds RouteCollection service to manage routes classes collection.
* Adds RouteInterface to provide a template for creating route class.
* Adds implementation routes example on Core Tester.
- To split route definition in class.
> routing: manage routes with classes

- projects/rero/ng-core/src/lib/core.module.ts
- projects/rero/ng-core/src/lib/text-read-more/text-read-more.component.html
- projects/rero/ng-core/src/lib/text-read-more/text-read-more.component.spec.ts
- projects/rero/ng-core/src/lib/text-read-more/text-read-more.component.ts
- projects/rero/ng-core/src/public-api.ts
Co-Authored-by: Benoit Erken <erken.benoit@gmail.com>
Create new "read more" component: truncate the text when it's too long and add a link to "show more"
> component: add "read more" component

- projects/rero/ng-core/src/lib/record/editor/toggle-wrapper/toggle-wrappers.component.ts
When toggle wraps some fields containing data model, the toggle should be enable but it isn't.
This fix solved this problem.
> editor: fix toggle wrapper behavior

- projects/rero/ng-core/src/lib/record/editor/toggle-wrapper/toggle-wrappers.component.ts
If the toggle applies only on 1 child field, the behavior of the toggle failed: the child field was not hided.
This fix resolves this problem.
> toggle-wrapper: fix issue with single child

- projects/rero/ng-core/src/lib/search-input/search-input.component.html
- projects/rero/ng-core/src/lib/search-input/search-input.component.ts
* Adds an input property to remove trailing and leading space if needed.
* Removes weird character in licence text of the template.
* Closes rero/rero-ils-ui#213.
https://tree.taiga.io/project/rero21-reroils/task/1386?kanban-status=1224894
Needs to be tested in rero-ils-ui: https://github.com/rero/rero-ils-ui/pull/219
See issue description: rero/rero-ils-ui#213
> search: fix query with trailing and leading space

- projects/rero/ng-core/src/lib/record/editor/array-type/array-type.component.html
- projects/rero/ng-core/src/lib/record/editor/array-type/array-type.component.ts
- projects/rero/ng-core/src/lib/record/editor/object-type/object-type.component.html
* Fixes missing stars after required field titles when the editor is displayed.
* Fixes the number of items after the hiding and showing array fields.
It should be equal to the minimum number of items defined in the JSONSchema.
* Fixes missing title for array of array fields.
Co-Authored-by: Gianni Pante <gianni.pante@rero.ch>
- Implements US: https://tree.taiga.io/project/rero21-reroils/us/1232?milestone=257446
- Deploy with rero-ils: https://github.com/rero/rero-ils/pull/864
- Check that a start is displayed next to the title.
- Check that the Publication statement is displayed correctly (array of array)
- Take an array element add several values, hide the field, show the field. The field should be as the initial state of the …
> editor: fix missing stars for required fields

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/ng-core-tester/src/app/home/home.component.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
- projects/rero/ng-core/src/lib/record/record.service.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search-page.component.html
- projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.service.spec.ts
- projects/rero/ng-core/src/lib/record/search/record-search.service.ts
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.html
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.ts
- projects/rero/ng-core/src/lib/widget/menu/menu.component.html
- projects/rero/ng-core/src/public-api.ts
* Adds nested aggregations support.
* Refactors RecordSearchComponent.
* Unsubscribes from observables when components are destroyed.
* Creates a RecordSearchService for handling aggregations filters.
* Adapts menu component in order to include query parameters.
* Sets aggregations buckets size to 8 in tester application.
* Fixes "combineLatest" RxJS function deprecation warnings.
* Exports RecordSearchService in public-api to use it outside ng-core.
* Initializes filters to launch first search on homepage.
> search: add nested aggregations support

- projects/rero/ng-core/src/lib/record/editor/interfaces.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
- projects/rero/ng-core/src/lib/translate/translate-language.service.spec.ts
- projects/rero/ng-core/src/lib/translate/translate-language.service.ts
- projects/rero/ng-core/src/lib/translate/translate-service.ts
* Translates values for the "language" field.
* Translates values for others enum fields.
* Exports FormlyModule and FormlyBootstrapModule for reuse in host application.
* Creates an interface representing a select option.
Co-Authored-by: Sébastien Délèze sebastien.deleze@rero.ch
> translations: translate values for enum fields

- projects/rero/ng-core/src/lib/record/autocomplete/autocomplete.component.html
- projects/rero/ng-core/src/lib/record/autocomplete/autocomplete.component.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.ts
* Adds the possibility of giving additional query parameters to filter
search.
* Corrects 'display more' function in nested facets.
To apply corrections asked by the PO group.
https://tree.taiga.io/project/rero21-reroils/task/1441?kanban-status=1224894
Needs https://github.com/rero/rero-ils-ui/pull/208 and https://github.com/rero/rero-ils/pull/852 + ebooks harvesting.
1. In admin view, do a search of a document. The result should be filtered by user's organisation.
2. Ebooks count should consider organisation filtering too.
1. Children (library) facet should be reduced to 10 items. Click on `more...` to display all of them and on `less...` to hide again.
See …
> document: filter search by organisation

- package-lock.json
- package.json
- projects/rero/ng-core/src/lib/record/autocomplete/autocomplete.component.ts
- projects/rero/ng-core/src/lib/record/record.service.ts
The list of suggestions are sometime not displayed when the server take
few milliseconds to respond. This has been fixed in a new version of the
third party library `ngx-bootstrap`.
Moreover when a document is selected the search should be executed.
* Fixes the display of the suggestion list for unquick server response.
* Executes the search query when a suggestion is clicked.
* Fixes minimal size value for REST API since "invenio-records-rest>1.4.2".
* Fixes console error when a query is removed by keeping backspace key
pressed.
- https://github.com/rero/rero-ils-ui/pull/253
- To fix: rero/rero-ils#788
- Go to a view containing an autocomplete component.
- Type slowly a query, after 3 chars the list of suggestions should be …
> autocomplete: fix suggestions are not displayed

- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/search-input/search-input.component.html
* Removes 'autofocus' html attribute.
* Sets the focus on search input.
* Closes rero/rero-ils#928.
To implement task 1462: https://tree.taiga.io/project/rero21-reroils/task/1462?kanban-status=1224894
To close https://github.com/rero/rero-ils/issues/928
Go to different brief views of professional interface.
Check that the focus is automatically set on the search input.
Go to the document editor.
Check that there is no conflict with the focus in the editor.
> search input: set focus on search input by default

- projects/rero/ng-core/src/lib/utils/utils.ts
Sometimes, some '$ref' frm the model are null values (This is the case
for 'restrict_pickup_to' on location schema if no restrict are defined).
In this case, the function 'extractIdOnRef' generates an error and
causes instability in the corresponding resource editor.
This commit resolves this problem.
Co-authored-by : Renaud Michotte <renaud.michotte@gmail.com>
> utils : update extractIdOnRef if value is null.

- projects/rero/ng-core/src/lib/record/detail/detail.component.html
- projects/rero/ng-core/src/lib/record/editor/editor.component.html
* Adapts record detail buttons according to UX chart.
* Adapts editor buttons according to UX chart.
- Go to the document detail page. Edit/delete buttons are now according to UX.
- Go to a resource editor (patron_types, vendors, ...). Save/Cancel buttons are now according to UX.
> editor: adapt editor according to UX chart

- projects/ng-core-tester/src/app/app-config.service.ts
- projects/ng-core-tester/src/assets/i18n/fr.json
- projects/ng-core-tester/src/environments/environment.prod.ts
- projects/ng-core-tester/src/environments/environment.ts
- projects/rero/ng-core/src/lib/core-config.service.ts
- projects/rero/ng-core/src/lib/translate/translate-loader.spec.ts
- projects/rero/ng-core/src/lib/translate/translate-loader.ts
* Removes `customTranslations` property.
* Adds `translationsURLs` to provide a list of remote translations.
* Changes the demo applications accordingly.
* Simplifies the tests.
- rero/rero-ils: https://github.com/rero/rero-ils/pull/997
- rero/rero-ils-ui: https://github.com/rero/rero-ils-ui/pull/271
- To allows a server to provide custom translations.
- Look at the application demo and see the translations configurations and if it is works.
> translations: add http translations support

- projects/rero/ng-core/src/lib/record/detail/detail.component.html
- projects/rero/ng-core/src/lib/record/editor/array-type/array-type.component.html
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/horizontal-wrapper/horizontal-wrapper.component.ts
- projects/rero/ng-core/src/lib/record/editor/object-type/object-type.component.html
- projects/rero/ng-core/src/lib/record/editor/toggle-wrapper/toggle-wrappers.component.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
* Adds horizontal wrapper to move editor labels next to the input.
* Compacts brief and detail views to not use the whole width of the window.
* Displays description in tooltips in editor.
Implements task 1473 of US1296
https://tree.taiga.io/project/rero21-reroils/us/1296?milestone=263424
https://tree.taiga.io/project/rero21-reroils/task/1473?kanban-status=1224894
Use https://github.com/rero/rero-ils/pull/983 and https://github.com/rero/rero-ils-ui/pull/267
Use `npm pack` or `npm link` to install this PR on rero-ils-ui, which needs to be installed in rero-ils after that.
Go to document editor and check that the labels are next to the inputs (same line, not above).
> ui: improve display of editor, brief and detail views

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
This PR fixes the redundant calls to 'preprocessRecord'. Before this PR
the preprocessRecord function was called each time the model was getted.
This will cause a call for each field present into the editor. This PR
fixes this problem calling preprocessRecord function only when the model
is setted or when it changes from the parent input.
> editor: fix preprocessRecord calls

- projects/rero/ng-core/src/lib/record/editor/array-type/array-type.component.html
- projects/rero/ng-core/src/lib/record/editor/array-type/array-type.component.ts
- projects/rero/ng-core/src/lib/record/editor/dropdown-label-editor/dropdown-label-editor.component.html
- projects/rero/ng-core/src/lib/record/editor/dropdown-label-editor/dropdown-label-editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/horizontal-wrapper/horizontal-wrapper.component.ts
- projects/rero/ng-core/src/lib/record/editor/multischema/multischema.component.ts
- projects/rero/ng-core/src/lib/record/editor/object-type/object-type.component.html
- projects/rero/ng-core/src/lib/record/editor/object-type/object-type.component.ts
* Adapts editor to use css class from jsonschema.
* Displays description in editor for multischema fields.
* Displays a background on mouse hover on title to highlight a block.
* Hide "add","hide"  and "show" buttons and shows them on mouse hover.
It's part of https://tree.taiga.io/project/rero21-reroils/us/1296?milestone=263424 (UX of editor)
Needs https://github.com/rero/rero-ils/pull/1006 and https://github.com/rero/rero-ils-ui/pull/267
1. Go to document editor
1. Check that fields of nth level are displayed inline. Example:
3. Check that other display is not broken.
> editor: display fields inline 

- projects/rero/ng-core/src/lib/record/detail/detail.component.html
- projects/rero/ng-core/src/lib/record/editor/array-type/array-type.component.html
- projects/rero/ng-core/src/lib/record/editor/array-type/array-type.component.ts
- projects/rero/ng-core/src/lib/record/editor/dropdown-label-editor/dropdown-label-editor.component.html
- projects/rero/ng-core/src/lib/record/editor/dropdown-label-editor/dropdown-label-editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/horizontal-wrapper/horizontal-wrapper.component.ts
- projects/rero/ng-core/src/lib/record/editor/multischema/multischema.component.ts
- projects/rero/ng-core/src/lib/record/editor/object-type/object-type.component.html
- projects/rero/ng-core/src/lib/record/editor/object-type/object-type.component.ts
- projects/rero/ng-core/src/lib/record/editor/toggle-wrapper/toggle-wrappers.component.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
* Adds horizontal wrapper to move editor labels next to the input.
* Compacts brief and detail views to not use the whole width of the window.
* Displays descriptions in tooltip in editor.
> merge US1296 to dev (UX of editor)

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/extensions.ts
This PR adds a custom validator to check if complex object are unique
into an array of objects. Comparing to UniqueValidator from ngx-formly,
this new validator allows to specify which objects keys should be used
to compare if values are unique into an array.
> validator : add custom unique validator for complex object.

- projects/rero/ng-core/src/lib/record/detail/detail.component.html
- projects/rero/ng-core/src/lib/record/detail/detail.component.ts
* Allows to redirect to the parent with an object or a string after record deletion.
* Closes rero/rero-ils#1024.
- To fix the redirect url after delete a record on detail view
> detailed view: redirect after record deletion

- projects/rero/ng-core/package.json
- projects/rero/ng-core/src/lib/record/search/aggregation/slider/slider.component.html
* Fixes an issue when aggregation range is displayed in Firefox.
* Adds `ngx-bootstrap-slider` library to peerDependencies.
> search: fix aggregation range

- projects/rero/ng-core/src/lib/widget/menu/menu.component.html
This commit defines two new options for any sub menu item : prefix and
suffix. Prefix will be display as dark bold text ; suffix will be
display as dark info text.
Co-authored_by: Renaud Michotte <renaud.michotte@gmail.com>
> menu: add prefix and suffix options on submenu item

- projects/rero/ng-core/src/lib/pipe/get-record.pipe.ts
* Adds a parameter to allow using headers in getRecord pipe.
To allow the use of headers in getRecord pipe.
Needs https://github.com/rero/rero-ils/pull/1046 and https://github.com/rero/rero-ils-ui/pull/283.
Create or edit a document with partOf field.
Check that the title of the host document is displayed.
> record: allow to use headers in getRecord pipe

- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- projects/rero/ng-core/src/lib/translate/i18n/de.json
- projects/rero/ng-core/src/lib/translate/i18n/en.json
- projects/rero/ng-core/src/lib/translate/i18n/en_US.json
- projects/rero/ng-core/src/lib/translate/i18n/fr.json
- projects/rero/ng-core/src/lib/translate/i18n/it.json
* Adds a configuration support to customize the number of results text.
* Adds a title on a search view when only one resource is displayed.
* Adds a new configuration to hide the title on the search page.
> search: make the number of results configurable

- projects/rero/ng-core/src/lib/record/editor/editor.service.ts
- projects/rero/ng-core/src/lib/record/editor/object-type/object-type.component.html
* Fixes invalid links for some entries from TOC/JumpTo component.
* Closes rero/rero-ils#1035
Ca-Authored-By: Renaud Michotte <renaud.michotte@gmail.com>
> editor: fix problem with jump to

- package-lock.json
- package.json
* Fixes vulnerability by upgrading `npm-registry-fetch` library to version equal or greater than 4.0.5.
> security: update dependencies

- projects/rero/ng-core/src/lib/widget/menu/menu.component.html
- projects/rero/ng-core/src/lib/widget/menu/menu.component.ts
* Adds Id option for menu
Co-Authored-by: Olivier DOSSMANN <git@dossmann.net>
US1565 Adapt checkout needs some ID in menu for testing purposes.
This commit adds Id option to menu entries.
> menu: add Id option for menu and submenu

- projects/rero/ng-core/src/lib/record/editor/add-field-editor/add-field-editor.component.html
- projects/rero/ng-core/src/lib/record/editor/add-field-editor/add-field-editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/extensions.ts
When setting up the translation, the processing of the options in the select menu was missing.
The translation of the labels is not done correctly on the long form when the user changes language.
* fixes translation of select menu.
* fixes translation of input field and button on the long form.
> editor: fix translation

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
Fixes the behaviour of the editor with 'oneOf' schema property: for
example, when selecting 'organisation' as author, the value of 'type'
needed to be selected manually. Now the correct value of type is
selected automatically. A similar behaviour is noted for 'mode of
issuance' maintype and subtype.
This PR is part of US1432 (task 1603)
https://tree.taiga.io/project/rero21-reroils/us/1432?milestone=268117
https://tree.taiga.io/project/rero21-reroils/task/1603?kanban-status=1224894
Needs https://github.com/rero/rero-ils/pull/1097 and https://github.com/rero/rero-ils-ui/pull/283
Login as a (system) librarian.
Go to the record editor.
Try several values for authors and mode of …
> editor: fix 'oneOf' behaviour

- projects/ng-core-tester/src/app/home/home.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
This part add a button or dropdown list on search page to export results.
* Adapts record search component and template.
* Adds `export as ...` on ng-core-tester home page.
Co-Authored-by: Lauren-D <laurent.dubois@itld-solutions.be>
https://tree.taiga.io/project/rero21-reroils/task/1616
> search: add button to export results

- projects/rero/ng-core/src/lib/record/editor/editor.service.ts
- projects/rero/ng-core/src/lib/record/editor/object-type/object-type.component.html
* Prefixes the `id` attribute for fields with `field-`, to make the toggle switch work again.
> editor: fix toggle switch issue

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
* Adds a new output to notify the parent component that the model and
the JSONSchema is loaded. This allows to avoid concurrency problem.
> editor: add new output when the editor is loaded

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/utils.ts
* Adds ordered properties for JSONSchema definitions.
* Fixes ordered properties for JSONSchema oneOf, anyOf.
* Sets horizontal labels only for the long mode editor.
> editor: add ordered property for definitions

- package-lock.json
- package.json
- projects/rero/ng-core/package.json
* Uses ngx formly 5.9.
* Makes the autocomplete component asynchronous to allows hot language
switch.
* Tuncates long labels in the add field components.
* Fixes autocomplete translations.
* Fixes field dropdown menu translations.
* Removes useless function and code.
* Fixes cssClass for multischema object.
* Moves the indentation value into the css instead of using bootstrap
classes.
* Fixes scroll and focus action when a new field is added or when a link
in the navigation is clicked.
* Stores the untranslated label in the formly field.
* Removes extra border for multischema element.
* Uses bootstrap variables to define the editor card.
* Adds a global editor class.
* Makes the editor component style global.
* Closes rero/rero-ils#1003.
* Cleans the initialization sequence for the …
> release: version 0.7.0

- projects/rero/ng-core/src/lib/record/editor/extensions.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
* Adds an extension to set specific id attributes to formly fields in order to select them more easily with Cypress.
https://tree.taiga.io/project/rero21-reroils/task/1622?kanban-status=1224894
Source: 
* https://github.com/ngx-formly/ngx-formly/issues/1150#issuecomment-416239430
* https://github.com/ngx-formly/ngx-formly/issues/1624#issuecomment-502771903
Go to an editor (documents, items) and check that the fields have an id attribute with joined keys.
Check the elements of arrays.
> editor: implement specific id attribute for formly fields

- projects/rero/ng-core/src/lib/dialog/dialog.component.html
- projects/rero/ng-core/src/lib/record/detail/detail.component.html
- projects/rero/ng-core/src/lib/record/editor/add-field-editor/add-field-editor.component.html
- projects/rero/ng-core/src/lib/record/editor/editor.component.html
- projects/rero/ng-core/src/lib/record/editor/extensions.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.html
* Adds id html attributes in templates for cypress usage.
* Corrects the method to inject custom id in the editor to be functional
with oneOf fields (issuance, authors).
To adapt the templates for tests with cypress.
Code review only
> template: add id html attribute for cypress usage

- projects/rero/ng-core/src/lib/record/editor/toggle-wrapper/toggle-wrappers.component.ts
- projects/rero/ng-core/src/lib/record/editor/type/datepicker-type.component.ts
- Fixes ToggleSwitch behavior when the wrapper is associated to a simple
field.
- Fixes DatePicker behavior when the field value is reset.
> editor: fix ToggleSwitch & DatePicker 

- projects/rero/ng-core/src/lib/record/editor/toggle-wrapper/toggle-wrappers.component.ts
As the description is already display as tooltip on toggle label, this
commit removes the description under the toggle button.
Co-Authored-by : Renaud Michotte <renaud.michotte@gmail.com>
> wrapper : remove description under toggle wrapper.

- projects/rero/ng-core/src/lib/core.module.ts
- projects/rero/ng-core/src/lib/error/error.component.html
- projects/rero/ng-core/src/lib/error/error.component.spec.ts
- projects/rero/ng-core/src/lib/error/error.component.ts
- projects/rero/ng-core/src/lib/error/error.ts
- projects/rero/ng-core/src/lib/record/detail/detail.component.html
- projects/rero/ng-core/src/lib/record/detail/detail.component.spec.ts
- projects/rero/ng-core/src/lib/record/detail/detail.component.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.html
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/record.service.spec.ts
- projects/rero/ng-core/src/lib/record/record.service.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- projects/rero/ng-core/src/public-api.ts
* Improves errors handling in search, detail and edit views.
* Adds an error component to display the error.
* Adds an interface for error objects.
* Removes `console.log` when a http error is catched.
* Sends an error object with status and title when a http error occurs.
* Types the parameters of subscribers to `getRecords` observable.
* Exports error component for using it in host's projects.
* Closes rero/sonar-ui#114.
> records: handle errors

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/utils/sort-by-keys.ts
* Improves selectWithSort by default if form options are defined.
* Improves sortByKey for diacritics characters.
* closes rero/rero-ils#1149
> editor: improve sorting of selects

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/remote-typeahead/remote-typeahead.component.html
- projects/rero/ng-core/src/lib/record/editor/remote-typeahead/remote-typeahead.component.spec.ts
- projects/rero/ng-core/src/lib/record/editor/remote-typeahead/remote-typeahead.component.ts
- projects/rero/ng-core/src/lib/record/editor/remote-typeahead/remote-typeahead.service.spec.ts
- projects/rero/ng-core/src/lib/record/editor/remote-typeahead/remote-typeahead.service.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
- projects/rero/ng-core/src/public-api.ts
* Adds a new typeahead component to be able to search a list of suggestion
using the backend.
> editor: add a typeahead component

- projects/rero/ng-core/src/lib/record/editor/add-field-editor/add-field-editor.component.html
- projects/rero/ng-core/src/lib/record/editor/add-field-editor/add-field-editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/array-type/array-type.component.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.html
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
Some fields containing values given with the input model should be visible
after the editor initializations. This is not the case with a recent version of
ngx formly. This is due to the use of bad hack `setTimeout` at several
places in the code. As ngx formly made the think cleaner these hacks have
been removed.
- Cleans hidden field list at the component destruction instead of
initialization.
- Removes the extra values in an array when the corresponding field is
hidden only when the values are reset.
- Some fields containing data are not displayed when a record is imported from an external source such as BNF in the `rero-ils-ui` project.
- Link the library to the `rero-ils-ui` start the admin server, import a record from the …
> editor: fix hidden field with value from the model

- projects/rero/ng-core/src/lib/record/editor/extensions.ts
When options labels are translated for select boxes, the group optionally present was dropped. This PR re-inject the group to keep options grouped.
* Adds `group` property after option is translated, if initially present.
> editor: fix options groups for select boxes

- projects/rero/ng-core/src/lib/record/editor/editor.component.scss
Instead of loading the whole Bootstrap library, only load functions, mixins and variables, to avoid that local styles of the editor override the main styles of the application.
* Removes global boostrap inclusion.
* Adds boostrap's functions, mixins and variables.
> editor: avoid loading the whole bootstrap library.

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/rero/ng-core/src/lib/record/record.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
This PR give the possibility to configure search fields. When a field (or more) is selected, the search is done on this field only, this is exclusive.
* Adds configuration for specific fields in routing.
* Adds an interface representing a search field.
* Displays the list of search fields above the aggregations filters.
* Builds a custom query if specific fields are selected.
> records: search on specific fields

- projects/rero/ng-core/src/lib/record/action-status.ts
- projects/rero/ng-core/src/lib/record/detail/detail.component.html
- projects/rero/ng-core/src/lib/record/detail/detail.component.ts
- projects/rero/ng-core/src/lib/record/record-ui.service.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.html
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.ts
This commit add the possibility to use a resource. If a resource can be
used, it is associated to an URL to use this resource. This commit also
add a button ('use') for each search result and in the detail view. This
button can be controlled by the 'canUse' parameter from the resource
configuration.
> views: add button to use a resource

- angular.json
- package.json
- projects/ng-core-tester/src/environments/environment.prod.ts
- projects/ng-core-tester/src/environments/environment.ts
- proxies/localhost.json
- proxies/mocklab.json
* Adds configurations for `localhost` and `mocklab` api in angular.json
* Adds a `serve` command in package.json to run `ng serve` with the `mocklab` configuration by default.
* Empties environment `apiBaseUrl` variable.
* Creates files for proxying to localhost and mocklab.
> tester: add proxies for API calls

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/rero/ng-core/src/lib/record/detail/detail.component.ts
- projects/rero/ng-core/src/lib/record/files/files.component.html
- projects/rero/ng-core/src/lib/record/files/files.component.spec.ts
- projects/rero/ng-core/src/lib/record/files/files.component.ts
- projects/rero/ng-core/src/lib/record/record.ts
This PR gives the possibility to edit metadata of files. These metadata are stored in record and thus can be different for each type of record.
* Configures a filter function in ng-core-tester to show an example how to filter files.
* Adds `metadata` property in `File` interface.
* Changes the way to activate files management. Now there's an object in configuration instead of `filesEnabled` property.
* Adds a configuration to avoid some fields to be displayed in file's information.
* Adds a configuration to order files.
* Adds a modal to edit file's metadata.
* Shows the metadata of the file in information container.
* Loads whole record to receive the metadata of each files.
* Loads JSON schema corresponding to record type, to initialize the editor.
Co-Authored-by: Sébastien Délèze …
> records: edit metadata of files

- projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
This PR allows to display a simple filter that contains only the count for the aggregation. Useful for filtering data based on a single value. For example, it can be used to filter users not associated to an organisation.
* Adds `doc_count` property to aggregation's interface.
* Displays filter as a simple checkbox.
> aggregations: display simple filter

- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
When the user clicks on Export Button, he gets 
an error 400 because url is not encoded.
Co-Authored-by: Benoit Erken <erken.benoit@gmail.com>
- Test the following URL: /professional/records/items?q=call_number:{"01924" TO "02000"}&page=1&size=10
and click on "Export as CSV". You should receive a file (and not an HTTP 400 Error)
> export: fix urlencode at export

- projects/rero/ng-core/src/lib/record/editor/editor.component.html
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
With this PR, the submit button of the editor is always active and validation is done when it is clicked. If validation fails, a toast message is displayed.
* Validates form before saving data.
* Removes unused `event` parameter in `submit` method.
* Makes submit button always active in template.
> records: validate data during editor submission

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/rero/ng-core/src/lib/record/files/files.component.html
- projects/rero/ng-core/src/lib/record/files/files.component.ts
This commit adds a configuration to determine if metadata of files can be updated for a type of resource.
* Adds a configuration to check if metadata of file can be updated.
* Allows to update metadata for `documents` in tester.
* Checks the new configuration before showing or not the update button.
> records: update files metadata

- projects/rero/ng-core/src/lib/record/editor/widgets/load-template-form/load-template-form.component.ts
* When we create a new holding/item from 'scratch', it will be linked
with a document. This is done by adding a 'document' argument into the
query url. Using a template removes this argument from query string and
cause an HTTP 400 error when trying to save because the editor lost the
link with the document. This commit solves this problem keeping all
existing arguments from query string when loading a template.
> template: allow using templates with new holdings/items

- projects/rero/ng-core/src/lib/record/editor/extensions.ts
If the options are of the observable type, no processing is applied.
> extension: Improve process options

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/type/select-with-sort-type.component.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
* Improves selectWithSort widget to implement order to multiple values.
* Closes rero/rero-ils#1231
> select widget: improve select with sort

- projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Improved tabs result page to allow multiple tabs on the same index.
> Tabs: several tabs on the same index.

- projects/rero/ng-core/src/lib/record/editor/wrappers/toggle-wrapper/toggle-wrappers.component.ts
When there are multiple toggle wrappers on the same page, the 'click'
behavior was wrong : whatever switch button clicked, only the first
element was toggle. This commit fixes this problem.
Authored-by: Renaud Michotte <renaud.michotte@gmail.com>
> editor: fix toggle wrapper if multiple

- projects/rero/ng-core/src/lib/record/record-ui.service.ts
* Fixes observable for input permissions on the route data configuration.
> permissions: fix permissions on the configuration

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.html
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.ts
* Adds tooltip on delete button of the search view to inform the user why deletion is not possible.
> search: add tooltip on delete button of brief view

- projects/rero/ng-core/src/lib/record/editor/type/object-type/object-type.component.ts
- projects/rero/ng-core/src/lib/record/editor/wrappers/toggle-wrapper/toggle-wrappers.component.ts
Despite if the toggle is switch off, the hidden fields were continue to
be controlled for the validation form process (data required, pattern,
...). This commit corrects this problem by disabling the
field.formControl (and children fields) when the toggle is switch off.
> editor: fix toggle wrapper field control behavior

- projects/rero/ng-core/src/lib/core.module.ts
- projects/rero/ng-core/src/lib/widget/sort-list/sort-list.component.html
- projects/rero/ng-core/src/lib/widget/sort-list/sort-list.component.spec.ts
- projects/rero/ng-core/src/lib/widget/sort-list/sort-list.component.ts
Creates a simple select widget to allow list sorting. This widget allows
to use an icon for options.
Authored-by: Renaud Michotte <renaud.michotte@gmail.com>
> widget: sort list widget.

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
* Fixes `hideShowEmptyField` method by not setting the model if the current model is not available, for simple fields.
* Activates editor long mode in tester as now it is not activated by default.
> editor: fix hide or show empty fields method

- projects/rero/ng-core/src/lib/record/record.service.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Supports multiple values for the pre filters for the API REST call.
For example `/api/documents/?library=1&library=2`.
Co-authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
- https://tree.taiga.io/project/rero21-reroils/us/1544?milestone=275632
- https://github.com/rero/rero-ils-ui/pull/425
> records: add multiple pre filters support

- projects/rero/ng-core/src/lib/record/files/files.component.html
Adds the `translate` pipe to the files metadata values, to have them translated. This is not useful in most case, but for select options it will be.
> documents: translate files metadata

- projects/rero/ng-core/src/lib/record/editor/widgets/load-template-form/load-template-form.component.ts
When we use the editor "cancel" button, the basic behavior navigate to
the previous URL. But, when we use the load template function, this
behavior cause to return to the same form (without templates URL
parameters) and you need to click again on "cancel" button.
This commit fixes this problem by skipping the "loading template URL"
from the browser history.
Closes rero/rero-ils#1453
Authored-by: Renaud Michotte <renaud.michotte@gmail.com>
> editor: fix cancel button behavior.

- projects/rero/ng-core/src/lib/record/editor/extensions.ts
Fixes two translations issues with the editor. When options for a select are defined as an
observable instead of an array, these options are not translated. Some of the option
properties could also be lost during the translation process.
Closes rero/rero-ils#1282
Authored-by: Renaud Michotte <renaud.michotte@gmail.com>
> editor: fix options translation problems.

- projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.service.ts
Displays a label in typeahead suggestions instead of the searched field which may not be present in results fields.
> editor: display a label in typeahead suggestions

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/ng-core-tester/src/app/app.module.ts
- projects/ng-core-tester/src/app/record/editor/editor.component.html
- projects/ng-core-tester/src/app/record/editor/editor.component.spec.ts
- projects/ng-core-tester/src/app/record/editor/editor.component.ts
- projects/ng-core-tester/src/app/record/editor/schema.json
- projects/ng-core-tester/src/app/service/app-menu.service.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
* Adds a new link in the application demo to show the editor with a
specific JSONSchema to demonstrate all the possibilities of the editor.
* Makes JSONSchema and editorSettings as Input for the editor component.
* Cleans the empty values in the emitted model.
* Set the defauls model and JSONSchema values if the URL do not contains
the record type.
* Closes #115.
- To diagnose easily the editor.
- Start the demo application and go to the record menu and click on the editor entry.
__Note__: the editor component file has been re-indented. Sorry for the review.
> editor: add schema example in the demo application

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/extensions.ts
- projects/rero/ng-core/src/lib/record/record.service.ts
* Adds catch error on record service on create, update and delete functions.
* Adds a new exception for the editor.
* Adds error message on the form.
> form: improve error message

- projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.scss
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
Improve the basic facet design :
* facet entry count right aligned to the facet box.
* text and counter is clickable to filter the search.
* improves general design.
> search: improve facet design.

- projects/rero/ng-core/src/lib/core.module.ts
- projects/rero/ng-core/src/lib/directives/ng-var.directive.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.html
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/public-api.ts
Due the previous changes, the dynamic save alternatives behavior was
broke : all alternatives call the same function instead of to use the
function define for each alternative. This commit fixes this problem.
This commit also introduces the "ngVar" directive to assign value to an
angular variable.
- Try to save a document as a new template. 
- After click on "save as template" alternative, the popup should appear. 
- Enter the template name you want to use and click on 'save' button.
> editor: fix save alternative problem.

- projects/rero/ng-core/src/lib/validator/time.validator.ts
The greaterThanValidator requires two arguments to find values to check.
But these arguments were not used. This commit fixes this behavior.
Closes rero/ng-core#320
> validators: fix greaterThan validator

- projects/rero/ng-core/src/lib/record/detail/detail.component.html
Moves the back link in record detail views on top left of the page content.
> records: move back link in record detail

- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
When a search result only 1 result, the result counter used always a
plural string. This commit fixes this behavior and get a singular '1
result' string a search return only 1 result.
Closes rero/ng-core#321
> search: fix result counter

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/extensions.ts
- projects/rero/ng-core/src/lib/record/editor/wrappers/horizontal-wrapper/horizontal-wrapper.component.ts
Adds new possibilities to horizontal field wrapper :
* parameter to hide the label (true|false).
* parameter to  customize the label using CSS classes.
Adds the 'datepicker' field type as an horizontal field for long mode
editor.
> editor: fix horizontal wrapper

- projects/rero/ng-core/src/lib/record/editor/editor.component.html
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
To avoid parent reference problem, the 'load template' button should be
only displayed for resource creation (and hide when a resource is edited).
Closes rero/rero-ils#1471.
> templates: restrict template loading to resource creation.

- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
To make the number of results understandable to the user,
the resource type tab no longer contains the total number of records.
- closes rero/rero-ils#1395
> search: remove total count on tab

- projects/ng-core-tester/src/app/home/home.component.ts
- projects/rero/ng-core/src/lib/dialog/dialog.component.ts
- projects/rero/ng-core/src/lib/menu/menu-widget/menu-widget.component.html
In a menu, when a dropdown entry was clicked, the page was reloaded. It
caused by an empty `href` tag. Using an empty `routerLink` binding
property fix this problem.
In the app tester, the button configuration for the modal actions was
missing. Additionally, add default values for modal button if
configuration doesn't provide any values.
> bug: correct dropdown menu issue and modal tester config.

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/extensions.ts
- projects/rero/ng-core/src/lib/record/editor/wrappers/form-field-wrapper/form-field-wrapper.component.ts
- projects/rero/ng-core/src/lib/record/editor/wrappers/horizontal-wrapper/horizontal-wrapper.component.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
* Adds custom validators support for repeatable fields.
* Fixes missing duplicate and trash support for form field in non
long mode.
> editor: add custom validators support

- projects/ng-core-tester/src/app/search-bar/search-bar.component.ts
- projects/rero/ng-core/src/lib/record/detail/detail.component.html
- projects/rero/ng-core/src/lib/record/detail/detail.component.ts
- projects/rero/ng-core/src/lib/record/detail/view/json.component.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.html
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.service.ts
- projects/rero/ng-core/src/lib/record/editor/widgets/load-template-form/load-template-form.component.ts
- projects/rero/ng-core/src/lib/record/files/files.component.ts
- projects/rero/ng-core/src/lib/record/record.service.spec.ts
- projects/rero/ng-core/src/lib/record/record.service.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.html
* Adds a configuration in routing data to set the context for the resource. This is useful for using resources in the context of `invenio-records-resources`.
* Uses `id` property of record instead of `metadata.pid` as this property not exists anymore with `invenio-records-resources`.
* Displays a default title for resource if `templateOptions.label` is not set.
> resources: add a config for resource context

- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Fixes second filter selection, which did not launch the search. This was caused by the search parameters subject which sends the original object instead of a copied one.
* Closes rero/rero-ils#1684.
> search: fix second filter selection

- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Takes into account the search filters when the check if the parameters have changed is done. Without that, the click on search filters buttons have no effect.
* Closes rero/sonar#510.
> search: fix search filters

- projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.component.html
- projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.component.ts
- projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.service.ts
* Makes the typeahead working with simple fields and not only `$ref`.
* Adds the support to create an entry and not select the existing ones.
* Improves the display of suggestions.
* Removes unused method `getValueAsHTML`.
> editor: improve typeahead

- projects/ng-core-tester/src/app/record/editor/schema.json
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
* Adds a new `doNotSubmitOnEnter` boolean templateOptions form property
to avoid form submission when the enter key is pressed.
> editor: some fields should not submit the form

- .prettierrc.json
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/type/textarea/textarea.component.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
* Adds counters in textarea for chars and words, depending on the configuration.
* Avoids to exceed the counts when typing.
* Checks for new resource context to avoid `pid` to be set in model.
> editor: count chars and words in textarea

- projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
A new parameter "aggregationsName" has been added
to the configuration to allow the customization of the aggregation name.
Supports a name property to set a custom title for an aggregation.
- allow the customization of the facet name
> aggregation: make the name customizable

- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
When the maximum rest results size is reached, export button is disabled.
On mouse hover, a message is displayed to the end user to explain why the button is disabled.
Co-Authored-by: Laurent Dubois <laurent.dubois@itld-solutions.be>
> search list: improve export button

- projects/ng-core-tester/src/app/record/editor/schema.json
- projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.html
- projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.ts
* Adds the support for multiple select options in custom select.
* Improves the filtered list by removing duplicate values.
* Refactors the way selected options are set.
> editor: add support for multiple select

- projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.component.ts
- projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.service.ts
Adds the currently edited record PID to suggestions backend request, to be able to do a specific process with the given PID.
> editor: add context for remote typeahead

- projects/rero/ng-core/src/lib/record/editor/type/array-type/array-type.component.html
- projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.html
- projects/rero/ng-core/src/lib/record/editor/type/object-type/object-type.component.html
* Adds selectors for object and array types.
* Surrounds custom select with a div to make it display block.
> editor: add selectors

- projects/rero/ng-core/src/lib/pipe/markdown.pipe.ts
Removes call to `nl2br` pipe as `marked` already does the job.
> markdown: fix pipe

- projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.html
- projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.scss
The `custom-select` display (select dropdown) doesn't look like other
input field. Fix the widget to get a very near display.
BEFORE
AFTER
> editor: fix `custom-select` widget display

- projects/ng-core-tester/src/app/record/editor/schema.json
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/extensions.ts
Allow to validate an array of object based on minimum or/and maximum
key/value pairs. Ex: for a document, allow to specify that a document
must have strictly one main title.
Closes rero/rero-ils#1361.
> editor: add min/max keys validator on object

- projects/rero/ng-core/src/lib/record/editor/widgets/add-field-editor/add-field-editor.component.html
> editor: no autocomplete on `add_field` field

- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/extensions.ts
- projects/rero/ng-core/src/lib/record/record.service.ts
Rather than a generic error message, try to use the message returned by
backend when an error is detected on the editor form.
> editor: improve error message

- projects/rero/ng-core/src/lib/search-input/search-input.component.html
When using the main search box and validate it using 'enter' key, the
small 'input search box' from document result page was also fired and
cause a double search. The second request removes all filters from URL.
Closes rero/rero-ils#2130.
> search: fix double enter fire event

- projects/rero/ng-core/src/lib/record/record.service.spec.ts
- projects/rero/ng-core/src/lib/record/record.service.ts
Adds the `facets` paramter to `getRecords` method. This parameter allow
to define which aggregation values should be included into API response.
By default, no aggregation should be include.
Co-authored-by: Sébastien Delèze <sebastien.deleze@rero.ch>
> api: add `facets` parameter to `getRecords`

- projects/rero/ng-core/src/lib/record/detail/detail.component.html
Does not display files management for a record if user cannot update this record.
> records: fix files permissions

- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
Fixes aggregation's name when name is set by the `aggregationsName` property in configuration. If aggregation's name is already set when retrieving aggregation from backend, the name is not overridden.
> records: fix aggregation name

- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
Fixes an aggregations filters error appearing sometimes when filters
are empty (null). The issue is fixed by initializing filters to an
empty array.
> search: fix aggregations filters error

- projects/rero/ng-core/src/lib/record/search/record-search.component.html
Allows to add a record when the record set is empty.
> search: allow add without records

- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
Allows to fill the aggregations order with an observable instead of a
simple array.
> search: observable for aggregations order

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Adds a `hideInTabs` configuration property to hide a resource from
the tabs in records search.
* Resets aggregations when the resource type is changed, for having
the aggregations for the right type.
> records: hide type in tabs

- projects/rero/ng-core/src/lib/record/editor/extensions.ts
- projects/rero/ng-core/src/lib/record/editor/services/editor.service.ts
- projects/rero/ng-core/src/lib/record/editor/type/object-type/object-type.component.ts
- projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.component.html
- projects/rero/ng-core/src/lib/record/editor/widgets/add-field-editor/add-field-editor.component.html
- projects/rero/ng-core/src/lib/record/editor/widgets/add-field-editor/add-field-editor.component.ts
* Reduces the resource and the time to load the editor.
* Adds a new method to set the list of the hidden fields.
* Removes the bad use of `setTimeout`.
* Adds scroll to suggestion list.
* Closes rero/rero-ils#1747.
* Closes rero/rero-ils#1908.
* Fixes autocomplete external link UI.
> editor: speed up the editor

- projects/rero/ng-core/src/lib/record/search/record-search.component.html
On small screen, the facets (normally displayed on left sidebar) moves
to the bottom of the screen. So, the search result hits are directly visible
on small screen.
> search: move facets at bottom on small screen

- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Does not add pre filters when they are present in the URL.
* Initializes filters with search filters during the loading application.
* Closes rero/rero-ils#2562.
* Closes rero/rero-ils#2527.
> search: fix search parameters on load

- projects/ng-core-tester/src/app/record/editor/schema.json
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
- projects/rero/ng-core/src/lib/validator/email.validator.ts
> editor: add email validator

- projects/rero/ng-core/src/lib/record/editor/extensions.ts
Options are processed only if they are of type Observable
or if the object dictionary contains the "label/value" key pair.
* Fixes formly extension options process.
> select: fix process options

- angular.json
- package-lock.json
- package.json
- projects/rero/ng-core/ng-package.json
- projects/rero/ng-core/package.json
- projects/rero/ng-core/src/lib/record/record.module.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/bucket-name.pipe.spec.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/bucket-name.pipe.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/list-filters/list-filters.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/list-filters/list-filters.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/list-filters/list-filters.component.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/slider/slider.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/slider/slider.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.service.ts
Signed-off-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
* Removes the parent filters when a filter is selected in a hierarchical
aggregation.
* Removes useless methods.
* The aggregationsExpand configuration can be a function.
* Adds indeterminate state to the parent filters.
* Stores the aggregationKey and parent properties in each bucket.
* Add filter list
* Removed ngx-bootstrap-slider
* Display banner no results in current page
Co-Authored-by: Valeria Granata <valeria@chaw.com>
> search: keep only the children filter and add filter list

- projects/rero/ng-core/src/lib/api/api.service.spec.ts
- projects/rero/ng-core/src/lib/api/api.service.ts
Adds method to retrieve an export endpoint API based on resource type.
> ApiService: Export endpoint

- projects/rero/ng-core/src/lib/record/search/aggregation/list-filters/list-filters.component.ts
> search filters: fix dates range format

- projects/rero/ng-core/src/lib/record/record.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/list-filters/list-filters.component.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/slider/slider.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.service.ts
* Adds some areas into the default `record-search` component (used to
render a search result) to allow content injection :
top-search-result, top-result, top-facets, bottom-result,
bottom-search-result.
* Add option to always hide a facet : In some case, we need to request
to backend about a facet, but this facet should never be displayed
by search components (other component can use content-injection to
display them).
> search : add customizable areas into search result page

- projects/ng-core-tester/src/app/routes/documents-route.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
Allow to define default aggregations to always add when user use the result page serach input form.
> results: allow default aggregation using the search input

- projects/ng-core-tester/src/app/record/editor/schema.json
- projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.component.html
- projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.component.ts
It is possible to configure filters directly in the jsonschema with a new entry "filters" in templateOptions.
> formly: add filter on remote typeahead

- projects/ng-core-tester/src/app/record/editor/schema.json
- projects/rero/ng-core/src/lib/record/editor/extensions.ts
In the jsonschema, it is possible to define the defaultValueExpression function to assign a default value to the field.
> formly: add a set default value

- projects/rero/ng-core/src/lib/component/abstract-can-deactivate.component.ts
- projects/rero/ng-core/src/lib/core.module.ts
- projects/rero/ng-core/src/lib/guard/component-can-deactivate.guard.spec.ts
- projects/rero/ng-core/src/lib/guard/component-can-deactivate.guard.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.spec.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/public-api.ts
A confirmation message is displayed if the user leaves the form without saving it.
* Removes spinner on editor.
* Changes the visiblity of the property in the editor to allow
abstracting the class.
* Closes rero/rero-ils#2104.
> editor: confirmation message when leaving

- projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- Allows `description` and `column` for typeahead suggestion.
- Small refactoring on `record-search` component.
> typeahead: allow more options for typeahead suggestion.

- projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.ts
> editor: fix groupable custom select.

- angular.json
- projects/rero/ng-core/src/lib/record/detail/detail.component.html
- projects/rero/ng-core/src/lib/record/detail/detail.component.ts
- projects/rero/ng-core/src/lib/record/files/file/file.component.html
- projects/rero/ng-core/src/lib/record/files/file/file.component.spec.ts
- projects/rero/ng-core/src/lib/record/files/file/file.component.ts
- projects/rero/ng-core/src/lib/record/files/files.component.html
- projects/rero/ng-core/src/lib/record/files/files.component.ts
- projects/rero/ng-core/src/lib/record/record.module.ts
- projects/rero/ng-core/src/lib/record/record.ts
* Fixes broken `ng` command such as `ng c`.
* Adds permissions support to the file component to hide action buttons.
> files: add permissions

- projects/rero/ng-core/src/lib/record/action-status.ts
- projects/rero/ng-core/src/lib/record/record-ui.service.ts
- projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.html
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.spec.ts
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.ts
* Adds 2 new parameters to the ActionStatus interface.
* Updates the precedence of canUpdate and canDelete functions.
* Updates add button to reflect new routerLink parameter.
* Adds a parameter to the deleteRecord function and modify the event.
> general: Managing multiple resources in a route

- angular.json
- package.json
- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/rero/ng-core/src/lib/record/record.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/list-filters/list-filters.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- proxies/wiremockapi.json
The mocklab service no longer exists. Its data have been migrated
to the new wiremock service.
* Fixes api mock for the tester.
* Changes search filters processing and display.
* Updates search filters on the document route.
> search filters: refactoring to be more generic

- projects/ng-core-tester/src/app/record/editor/schema.json
- projects/ng-core-tester/src/assets/i18n/de.json
- projects/ng-core-tester/src/assets/i18n/en.json
- projects/ng-core-tester/src/assets/i18n/fr.json
- projects/ng-core-tester/src/assets/i18n/it.json
- projects/rero/ng-core/src/lib/record/editor/extensions.ts
- projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.html
- projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.ts
The "Select an option…" option remains displayed when values are selected. This option is used to reset the data.
* Keeps selected items in order.
* Improves the select menu by always displaying the menu item "Select an option…".
* Fixes missing translation.
* closes #568.
> editor: fix select sort

- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
Default filters are added only if there is no search.
* Closes rero/rero-ils#3617.
> fix(search): add default filters

- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Closes https://github.com/rero/rero-ils/issues/3265.
> export: fix the url generation

- projects/ng-core-tester/src/app/record/editor/schema.json
- projects/rero/ng-core/src/lib/record/editor/type/date-time-picker-type.component.ts
- projects/rero/ng-core/src/lib/record/editor/type/datepicker-type.component.ts
* Fixes wrong invalid field when the input field is emptied.
* Adds `dataType` for the primeng date picker.
* Enhances the editor examples.
> editor: fix wrong validation for the datepicker component

- projects/ng-core-tester/src/app/record/editor/recordData.json
- projects/ng-core-tester/src/app/record/editor/schema.json
- projects/rero/ng-core/src/lib/record/editor/editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/extensions.ts
- projects/rero/ng-core/src/lib/record/editor/widgets/add-field-editor/add-field-editor.component.ts
* Avoids the possiblity to remove or add a field with an hide expression (tash button on the label component).
* Adds an exemple in the demo editor.
* Does not add a field with an hide expression during the edit initialization. In the previous versions the field was in the editor and in the completion menu.
> editor: fix can remove field when a hide expression exists

- projects/rero/ng-core/src/lib/record/record.module.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- projects/rero/ng-core/src/public-api.ts
* Exports several component to be able to derivate the RecordSearchComponent class.
> search: export search components to other modules

- projects/ng-core-tester/src/app/app-routing.module.ts
- projects/ng-core-tester/src/app/app.component.html
- projects/ng-core-tester/src/app/routes/documents-route.ts
- projects/ng-core-tester/src/app/search-bar/search-bar.component.html
- projects/ng-core-tester/src/app/search-bar/search-bar.component.ts
- projects/rero/ng-core/assets/scss/_editor.scss
- projects/rero/ng-core/assets/scss/_theme.scss
- projects/rero/ng-core/assets/scss/_typography.scss
- projects/rero/ng-core/assets/scss/ng-core.scss
- projects/rero/ng-core/src/lib/prime-ng-core-module.ts
- projects/rero/ng-core/src/lib/record/editor/editor.component.scss
- projects/rero/ng-core/src/lib/record/editor/formly/primeng/select/select.ts
- projects/rero/ng-core/src/lib/record/editor/wrappers/form-field-wrapper/form-field-wrapper.component.ts
- projects/rero/ng-core/src/lib/record/export-button/export-button.component.html
- projects/rero/ng-core/src/lib/record/search-autocomplete/search-autocomplete.component.scss
- projects/rero/ng-core/src/lib/record/search-autocomplete/search-autocomplete.component.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/buckets/buckets.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/date-range/date-range.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/date-range/date-range.component.ts
- projects/rero/ng-core/src/lib/record/search/aggregation/slider/slider.component.html
- projects/rero/ng-core/src/lib/record/search/aggregation/slider/slider.component.ts
- projects/rero/ng-core/src/lib/record/search/menu-sort/menu-sort.component.html
- projects/rero/ng-core/src/lib/record/search/menu-sort/menu-sort.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts
- projects/rero/ng-core/src/lib/record/search/record-search.component.html
- projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.html
* Removes css layers.
* Adds boostrap exceptions.
* Uses ils data for the tester.
* Removes boostrap classes remainders.
* Uses a menu for the export format component.
* Adds enter event support for the autocomplete component.
* Adjusts the suggestion panel size to the input search autocomplete input.
* Uses fieldset for the facets.
* Fixes display more.
* Adds range preset buttons.
* Fixes the date range layout.
* Uses a menu for the sort component.
* Makes the search view more responsive.
> primeng: adjust css styles

- projects/rero/ng-core/src/lib/record/editor/type/password-generator-type.component.ts
* adds class on props.
* adds a clipboard message when the password is generated.
> formly(password-generator-type): add class on props

- projects/rero/ng-core/src/lib/record/editor/formly/primeng/select/select.ts
When the group parameter is activated and the OptionValue parameter is set, the placeholder is no longer displayed.
> fix(formly): remove optionValue parameter

- package-lock.json
- projects/ng-core-tester/src/app/record/editor/schema.json
- projects/rero/ng-core/src/lib/prime-ng-core-module.ts
- projects/rero/ng-core/src/lib/record/editor/formly/primeng/multi-select/multi-select.ts
- projects/rero/ng-core/src/lib/record/editor/formly/primeng/remote-autocomplete/remote-autocomplete.ts
- projects/rero/ng-core/src/lib/record/editor/formly/primeng/select/select.ts
- projects/rero/ng-core/src/lib/record/editor/formly/primeng/tree-select/tree-select.ts
- projects/rero/ng-core/src/lib/record/editor/widgets/add-field-editor/add-field-editor.component.html
- projects/rero/ng-core/src/lib/record/editor/widgets/add-field-editor/add-field-editor.component.ts
- projects/rero/ng-core/src/lib/record/editor/widgets/label/label.component.ts
* Fixes missing placeholder for grouped dropdown.
* Fixes missing hidden fields in the label editor component.
> primeng: fix editor

- projects/ng-core-tester/src/app/record/editor/schema.json
- projects/rero/ng-core/src/lib/prime-ng-core-module.ts
- projects/rero/ng-core/src/lib/record/editor/formly/primeng/date-picker/date-picker.spec.ts
- projects/rero/ng-core/src/lib/record/editor/formly/primeng/date-picker/date-picker.ts
- Uses fluid instead of full width for the datepicker.
- Removes the minimum width on the date picker panel.
> fix(editor): datepicker should be smaller instead of taking the whole width of the screen

- projects/rero/ng-core/src/lib/record/editor/extensions.ts
- projects/rero/ng-core/src/lib/record/editor/type/array-type/array-type.component.html
- projects/rero/ng-core/src/lib/record/editor/type/markdown/markdown.component.ts
- projects/rero/ng-core/src/lib/record/editor/type/object-type/object-type.component.html
- projects/rero/ng-core/src/lib/record/record.module.ts
The editor's long mode uses the card to set separations. In the case of the card, don't delete the form-wrapper that displays alerts.
* Closes rero/rero-ils#3900.
> fix(editor): don't remove form field wrapper
