rero/ng-core

projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.html
* FIX Fix issue in aggregation filters not containing a "buckets" entry.
Signed-off-by: Sébastien Délèze <sebastien.deleze@rero.ch>
=> search: Aggregation filters issue

projects/rero/ng-core/package-lock.json, projects/rero/ng-core/package.json
* Updates the package version to 0.0.6.
=> project: publish new version

projects/rero/ng-core/src/lib/utils/utils.ts, projects/rero/ng-core/src/public-api.ts
=> utils: Add function extractIdOnRef

projects/ng-core-tester/src/app/app-routing.module.ts, projects/rero/ng-core/src/lib/dialog/dialog.component.html, projects/rero/ng-core/src/lib/dialog/dialog.component.ts, projects/rero/ng-core/src/lib/record/record-status.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.ts, projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.html, projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.spec.ts, projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.ts
* Returns an observable in delete callback function.
* Adds an information message in case of record cannot be deleted.
=> records: implement record delete decision

package-lock.json, package.json, projects/rero/ng-core/src/lib/core-config.service.ts, projects/rero/ng-core/src/lib/record/detail/detail.component.html, projects/rero/ng-core/src/lib/translate/i18n/de.json, projects/rero/ng-core/src/lib/translate/i18n/en.json, projects/rero/ng-core/src/lib/translate/i18n/en_US.json, projects/rero/ng-core/src/lib/translate/i18n/fr.json, projects/rero/ng-core/src/lib/translate/i18n/it.json, projects/rero/ng-core/src/lib/translate/translate-loader.ts, projects/rero/ng-core/src/lib/translate/translate-util.spec.ts, projects/rero/ng-core/src/lib/translate/translate-util.ts, projects/rero/ng-core/src/lib/widget/menu/menu.component.html, projects/rero/ng-core/src/lib/widget/menu/menu.component.spec.ts, projects/rero/ng-core/src/public-api.ts
* add property defaultLanguage on config service
* change private to public on translations property translateLoader
* add translate pipe on menu component
* add translate util class
=> translate: add some elements for translation functionality

projects/rero/ng-core/src/lib/shared.module.ts, projects/rero/ng-core/src/lib/translate/date-translate-pipe.spec.ts, projects/rero/ng-core/src/lib/translate/date-translate-pipe.ts, projects/rero/ng-core/src/lib/translate/translate-service.spec.ts, projects/rero/ng-core/src/lib/translate/translate-service.ts, projects/rero/ng-core/src/public-api.ts
=> translate: add translate service and date translate pipe

projects/ng-core-tester/src/app/app-routing.module.ts, projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.html, projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.spec.ts, projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.ts, projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.html, projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.ts, projects/rero/ng-core/src/public-api.ts
* Changes icon on show document action
* Adds parameter aggregations on routing configuration
* Adds translation on language aggregation
=> many: improvements

projects/rero/ng-core/README.md
* Adds documentation to README.md file.
=> project: documentation

projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Shows an error in records search when API is not responding.
* Fixes issue #3
Co-Authored-by: Sébastion Délèze <sebastien-deleze@rero.ch>
=> records: show error when API is not responding.

projects/ng-core-tester/src/app/app-routing.module.ts, projects/rero/ng-core/src/lib/record/detail/detail.component.spec.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Removes linkPrefix parameter as it is not more necessary.
=> records: remove linkPrefix parameter

projects/rero/ng-core/src/lib/record/detail/detail.component.ts, projects/rero/ng-core/src/lib/record/record-ui.service.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.ts, projects/rero/ng-core/src/public-api.ts
* Exports RecordUiService for using it outside ng-core.
* Changes parameters order on deleteRecord for consistency with RecordService::delete.
Co-Authored-by: Sébastion Délèze sebastien-deleze@rero.ch
=> records: export RecordUiService

projects/rero/ng-core/src/lib/record/editor/editor.component.ts, run-tests.sh
* Exports service as protected to allow inheritance for the editor
component.
* Adds pack command for the test script as sometimes new error appears
here.
- To be able to redefine the editor component in an other project.
=> editor: allow editor component inheritance

.github/PULL_REQUEST_TEMPLATE.md
* BETTER Updates PR template to include translation process.
To update pr template in order to include translation process.
N/A
=> template: update pr template

projects/rero/ng-core/src/lib/record/search/record-search.component.ts
From previous refactoring the result page was not reloaded after a
angular router navigation.
=> records: fix result reload after url changes

package-lock.json, projects/ng-core-tester/src/app/app-routing.module.ts, projects/ng-core-tester/src/app/home/home.component.html, projects/ng-core-tester/src/app/record-wrapper/record-wrapper.module.ts, projects/ng-core-tester/src/app/record/document/document.component.ts
* Creates a wrapper for RecordModule to avoid error on build with AOT.
* Fixes issues when building with AOT.
=> routing: fix error on production build

projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/record-ui.service.ts
* Adds new function in the config route parameters to preprocess a
record before the edition.
* Fixes redirection from the editor.
* Remove useless parameter description.
Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch
=> editor: can modify a record data before edition

projects/rero/ng-core/src/lib/record/editor/editor.component.ts
* Corrects update permission check.
Part of https://github.com/rero/rero-ils-ui/issues/43:
25. reroilstest@gmail.com cannot edit an freshly created item for example: https://ilsdev.test.rero.ch/professional/records/documents/detail/13207 , but can remove it
Try to edit an item (freshly created or old one).
=> editor: fix update permission

projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Allows to configure the search input visibility at the route or at the
type level.
- To fix: https://github.com/rero/rero-ils-ui/issues/43. Persons search input visibility.
=> records: set the search input visibility

projects/rero/ng-core/src/lib/record/search/record-search.component.html
- Fixes translation on resource label tab
- Check translation on tab.
=> resource tab label: translation

projects/ng-core-tester/src/app/app-routing.module.ts, projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- Adds configuration on routing data to customize elements.
- Test pagination
=> pagination: add configuration to customize elements

projects/rero/ng-core/src/lib/record/editor/mef/mef.component.ts
* Fixes mef authors not displayed in editor.
Mef authors are not displayed in editor.
Go to editor from harvested record and check authors.
=> document: fixes editor

projects/rero/ng-core/src/lib/record/editor/editor.component.html, projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/editor/mef/mef.component.html
* Fixes import mef using MEFComponent. This is a temporary fix until the
use of ngx-formly.
=> editor: fix mef component

projects/rero/ng-core/src/lib/record/editor/bootstrap4-framework/bootstrap4-framework.component.html
* Fixes translation problem on 'required fields' string
* Closes #572 (https://github.com/rero/rero-ils/issues/572)
=> translation : fix translation problem

projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/record-ui.service.spec.ts, projects/rero/ng-core/src/lib/record/record-ui.service.ts, projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.spec.ts
* Allows to give a redirection url after saving a resource.
https://tree.taiga.io/project/rero21-reroils/task/1116?kanban-status=1224895
Check usage with https://github.com/rero/rero-ils-ui/pull/92
=> record: adapt redirection after saving a resource

projects/ng-core-tester/src/app/app-routing.module.ts, projects/ng-core-tester/src/app/app.component.ts, projects/rero/ng-core/src/lib/record/record.service.ts
* Adds create, update and delete events on record service.
* Fixes absolute url on get schema form on record service.
- Adds events on record service
- Create, update and delete record and show notification
=> record: add events on record service

package-lock.json, package.json, projects/rero/ng-core/src/lib/service/crypto-js.service.spec.ts, projects/rero/ng-core/src/lib/service/crypto-js.service.ts, projects/rero/ng-core/src/lib/service/local-storage.service.spec.ts, projects/rero/ng-core/src/lib/service/local-storage.service.ts, projects/rero/ng-core/src/public-api.ts
* Adds new parameter secretPassphrase on core config.
* Adds new service to encrypt and decrypt data.
* Adds new service local storage.
- to store data on local storage
=> service: add cypto and local storage functionality

projects/rero/ng-core/package.json, projects/rero/ng-core/src/lib/service/local-storage.service.spec.ts, projects/rero/ng-core/src/lib/service/local-storage.service.ts
- Updates message on event onSet.
- Adds tests on event.
=> localStorage: Improve message on event onSet

projects/rero/ng-core/src/lib/record/search/record-search.component.html
* Fixes the search display on small devices.
=> records: search responsiveness

projects/rero/ng-core/src/lib/record/search/record-search-page.component.spec.ts, projects/rero/ng-core/src/lib/service/local-storage.service.spec.ts
* Fixes tests on RecordSearchPageComponent and LocalStorageService.
=> tests: fix tests

projects/rero/ng-core/src/lib/record/search/record-search.component.html
- Wrong text on first page link
- Check the correct text on first page link
=> pagination: fix text on first page link

projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/record.module.ts
* Adds mark the editor model as input.
* Exports the editor component to be used in an external application.
* Removes useless imports.
=> editor: expose the model as input component

projects/rero/ng-core/src/lib/record/editor/object-type/object-type.component.ts
- Removes trash button for non long editors
=> editor: hide trash button for non long editors

projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/editor/object-type/object-type.component.ts
* Fixes "Jump To" navigation for an existing record.
* Fixes hidden fields at startup.
=> editor: fix initial state

.github/workflows/main.yml
* Triggers a workflow when a pull request is pushed.
=> project: trigger workflow on pushing pull request

projects/rero/ng-core/src/lib/record/editor/editor.component.ts
=> editor: support validator with expression and message

projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Reloads list of records when a record is deleted in brief views.
=> records: fix record deletion issue

projects/rero/ng-core/src/lib/search-input/search-input.component.html, projects/rero/ng-core/src/lib/search-input/search-input.component.ts
* Sets focus to true or false to the input element.
https://tree.taiga.io/project/rero21-reroils/task/1272?kanban-status=1224894
See https://github.com/rero/rero-ils-ui/pull/123
=> search input: set focus

projects/rero/ng-core/README.md
* Corrects some errors in documentation.
=> documentation: corrections

projects/ng-core-tester/src/app/app-routing.module.ts, projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Allows to customize fields by implementing a map function in route configuration.
=> editor: customize fields by resource

projects/ng-core-tester/src/app/app-routing.module.ts, projects/rero/ng-core/src/lib/record/editor/editor.component.ts
* Fixes an issue when a field is customized by the map function.
=> editor: Fix issue in field customization

.github/workflows/main.yml, README.md
* Changes badge for the continuous integration, from Travis CI to Github actions.
=> ci: Change badge

projects/rero/ng-core/src/lib/record/editor/add-field-editor/add-field-editor.component.html
- https://github.com/rero/rero-ils-ui/issues/108, 19
- Check document editor, fields selection section.
=> editor: add class overflow-hidden on field button select

projects/rero/ng-core/src/lib/widget/menu/menu.component.html
=> menu: add option on sub menu to align with a class definition

projects/rero/ng-core/src/lib/record/editor/add-field-editor/add-field-editor.component.ts, projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/editor/editor.service.ts, projects/rero/ng-core/src/lib/record/editor/extensions.ts, projects/rero/ng-core/src/lib/record/record.module.ts
- Adds new onPopulate hooks.
- Shows a hidden field when a value exists in the model.
- To fix the fields visibility on model changes.
=> editor: fix field visibility on the model change

projects/rero/ng-core/src/lib/record/editor/extensions.ts, projects/rero/ng-core/src/public-api.ts
* Fixes ngx-formly extension support with aot angular compile option.
This is related to: https://github.com/ngx-formly/ngx-formly/issues/1624
=> editor: fix formly extension call with aot

projects/rero/ng-core/src/lib/record/editor/editor.component.html, projects/rero/ng-core/src/lib/record/editor/editor.component.ts
The editor component add a new output to detect the change in the model.
This is usefull to create a custom editor that need to detect changes
made by a user in the editor.
=> editor: add a new event when the model change

projects/ng-core-tester/src/app/app-routing.module.ts, projects/ng-core-tester/src/app/home/home.component.html, projects/ng-core-tester/src/app/routes/documents-hevs-route.ts, projects/ng-core-tester/src/app/routes/documents-route.ts, projects/rero/ng-core/src/lib/record/detail/detail.component.html, projects/rero/ng-core/src/lib/record/detail/detail.component.spec.ts, projects/rero/ng-core/src/lib/record/detail/detail.component.ts, projects/rero/ng-core/src/lib/record/record-routing.module.ts, projects/rero/ng-core/src/lib/record/search/record-search-page.component.spec.ts, projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.ts, projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.html, projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.ts
- Change boolean to observable.
- Change parameter on routing to check disabled admin actions.
=> routing: change adminMode parameter boolean to observable

package-lock.json, package.json
* Upgrades "acorn" dependency to version 6.4.1 or later.
* Upgrades "minimist" dependency to version 0.2.1 or later.
Co-Authored-by: Sébastien Délèze sebastien.deleze@rero.ch
=> project: fix security issues

projects/rero/ng-core/src/lib/record/record.service.ts
* Provides a size of "1" to avoid an error with "invenio-records-rest" after version 1.4.2.
=> editor: change size in unique value check

angular.json, package-lock.json, package.json, projects/rero/ng-core/src/lib/record/record.module.ts, projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.html, projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.ts, projects/rero/ng-core/src/lib/record/search/aggregation/slider/slider.component.html, projects/rero/ng-core/src/lib/record/search/aggregation/slider/slider.component.spec.ts, projects/rero/ng-core/src/lib/record/search/aggregation/slider/slider.component.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.ts, projects/rero/ng-core/src/lib/translate/i18n/de.json, projects/rero/ng-core/src/lib/translate/i18n/en.json, projects/rero/ng-core/src/lib/translate/i18n/en_US.json, projects/rero/ng-core/src/lib/translate/i18n/fr.json, projects/rero/ng-core/src/lib/translate/i18n/it.json, tsconfig.json
* Provides a slider in aggregation of type `slider` for searching between range of numbers.
* Adds `ngx-bootstrap-slider` library.
* Sets `skipLibCheck` to false to avoid error during compilation with the new library.
=> search: aggregation slider

package-lock.json, package.json
* Upgrades `kind-of` library to version 6.0.X.
=> security: update dependencies

projects/rero/ng-core/src/lib/record/autocomplete/autocomplete.component.ts
* Closes the dropdown containing the suggestion list after search query.
* Renames parameters to make it more understandable.
* Closes rero/rero-ils/#898.
- To fix: https://github.com/rero/rero-ils/issues/898
=> autocomplete: close the suggestion list

package-lock.json, package.json, projects/ng-core-tester/src/app/app.component.html, projects/ng-core-tester/src/app/home/home.component.html, projects/ng-core-tester/src/app/home/home.component.ts, projects/rero/ng-core/package.json, projects/rero/ng-core/src/lib/core.module.ts, projects/rero/ng-core/src/lib/record/detail/detail.component.ts, projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/record-ui.service.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Adds `ngx-spinner` library dependency.
* Registers and exports spinner module in core module.
* Adds an example in home page.
=> project: add `ngx-spinner` library

package-lock.json, package.json, projects/rero/ng-core/package.json
Downgrades the ngx-spinner version for compatibility with Angular 8.
Co-Authored-by: Lauren-D <laurent.dubois@itld-solutions.be>
=> project: downgrade ngx-spinner version

projects/ng-core-tester/src/app/app-routing.module.ts, projects/rero/ng-core/src/lib/record/record-ui.service.ts, projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.ts
- add possibility to make all permissions on single action.
=> record: add permissions parameter to global control access

projects/rero/ng-core/src/lib/record/editor/editor.component.ts
* Closes rero/rero-ils#1003.
* Cleans the initialization sequence for the editor.
- To fix: https://github.com/rero/rero-ils/issues/1003
=> editor: fix data loss for repeatable fields

projects/rero/ng-core/src/lib/record/editor/editor.component.html, projects/rero/ng-core/src/lib/record/editor/editor.component.scss, projects/rero/ng-core/src/lib/record/editor/editor.component.ts
To be able to identify easily an important field a new editor-title class
can be added in the JSONSchema in order to display the corresponding
field as a bootstrap card.
* Uses bootstrap variables to define the editor card.
* Adds a global editor class.
* Makes the editor component style global.
- https://tree.taiga.io/project/rero21-reroils/task/1560
=> editor: add card support

projects/rero/ng-core/src/lib/record/editor/extensions.ts
In some cases, such as anyOf or a select HTML component populated from
the backend, the editor library returns an asynchronous variable
(Observable). This commit fixes the editor crash for theses
particular cases.
- To fix editor crashes for asynchronous options values.
- Use it in rero-ils-ui and open the patron editor. It should not crash.
=> editor: fix asynchronous translations options

projects/rero/ng-core/src/lib/record/editor/extensions.ts
* Fixes asynchronous select translations after a language change.
=> editor: fix async select translations

README.md
* Adds a weblate badge to the README file.
=> documentation: add a weblate badge

projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Fixes the export urls by adding the search query parameter to filter
the exported results.
=> search list: fix export urls

projects/rero/ng-core/src/lib/record/editor/extensions.ts
* Adds numerical position on key generation for OneOf.
- Fix generate id on form field
- Check id on form
=> formly: improve id generator

projects/rero/ng-core/src/lib/translate/i18n/de.json, projects/rero/ng-core/src/lib/translate/i18n/en.json, projects/rero/ng-core/src/lib/translate/i18n/en_US.json, projects/rero/ng-core/src/lib/translate/i18n/fr.json, projects/rero/ng-core/src/lib/translate/i18n/it.json
* Updates translations catalogs for all languages.
=> translations: update catalogs

projects/rero/ng-core/src/lib/record/record.ts, projects/rero/ng-core/src/lib/record/search/record-search-page.component.html, projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.ts, projects/rero/ng-core/src/public-api.ts
* Adds ng-content on result page.
* Adds a new event to transmit the result of search.
=> record search: implement ng-content on page

projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.component.html, projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.component.ts
* Fixes Typeahead value search with multiple items on add function.
* Adds a validator dateMustBeLessThan.
* Adds a validator dateMustBeGreaterThan.
=> editor: improve typeahead and add new date validators

projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/editor/type/datepicker-type.component.ts
* Fixes dateMustBeLessThan and dateMustBeGreaterThan validators.
* Changes updateOn parameter to blur.
=> validator: fix date validators

projects/rero/ng-core/src/lib/record/detail/detail.component.ts
* Fixes the type on getRecord if index is present on configuration.
=> record: fix type query with index on getRecord

projects/rero/ng-core/src/lib/record/autocomplete/autocomplete.component.ts, projects/rero/ng-core/src/lib/record/record.service.ts
* Adds 2 parameters on the definition of a search
configuration for more flexibility.
=> search: improve autocompletion

CHANGELOG.md, package-lock.json, package.json, projects/rero/ng-core/package.json
=> release: version 0.14.0

projects/ng-core-tester/src/app/service/menu.service.ts, projects/rero/ng-core/src/lib/core.module.ts, projects/rero/ng-core/src/lib/menu/extension/core-extension.ts, projects/rero/ng-core/src/lib/menu/extension/extension-interface.ts, projects/rero/ng-core/src/lib/menu/menu-factory.spec.ts, projects/rero/ng-core/src/lib/menu/menu-item-interface.ts, projects/rero/ng-core/src/lib/menu/menu-item.spec.ts, projects/rero/ng-core/src/lib/menu/menu-item.ts, projects/rero/ng-core/src/lib/menu/menu-widget/menu-widget-prefix-suffix/menu-widget-prefix-suffix.component.html, projects/rero/ng-core/src/lib/menu/menu-widget/menu-widget-prefix-suffix/menu-widget-prefix-suffix.component.spec.ts, projects/rero/ng-core/src/lib/menu/menu-widget/menu-widget-prefix-suffix/menu-widget-prefix-suffix.component.ts, projects/rero/ng-core/src/lib/menu/menu-widget/menu-widget.component.html, projects/rero/ng-core/src/lib/menu/menu-widget/menu-widget.component.ts, projects/rero/ng-core/src/public-api.ts
Allows you to add prefix and suffix on the menu item.
- Prefix and Suffix on menu item
- Check on ng-core-tester
=> menu: add prefix and suffix

projects/rero/ng-core/src/lib/record/editor/wrappers/toggle-wrapper/toggle-wrappers.component.ts
- To translate label on toggle switch
=> toggle-switch: translate label and description

projects/ng-core-tester/src/app/service/menu.service.ts, projects/rero/ng-core/src/lib/menu/menu-item-interface.ts, projects/rero/ng-core/src/lib/menu/menu-item.spec.ts, projects/rero/ng-core/src/lib/menu/menu-item.ts, projects/rero/ng-core/src/lib/menu/menu-widget/menu-widget.component.html
Allows to add parameters to the url when routerLink is active.
=> menu: add query parameters

projects/ng-core-tester/src/app/record/editor/editor.component.spec.ts, projects/rero/ng-core/src/lib/menu/menu-widget/menu-widget-prefix-suffix/menu-widget-prefix-suffix.component.spec.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.ts
=> search: fix multiple backend call

projects/ng-core-tester/src/app/record/editor/schema.json
Adds issues in editor tester to reproduce some cases encountered in SONAR application.
=> editor: add issues in tester

projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Fixes errors when the search results view is loaded for the first time.
=> search: fix search result navigation

projects/rero/ng-core/src/lib/menu/menu-widget/menu-widget.component.html
* Restores id html attributes for cypress tests.
=> tests: fix cypress tests

projects/rero/ng-core/src/lib/record/files/files.component.ts
* Sets a default upload max size for files to 500Mb.
* Closes rero/sonar#412.
=> files: set default upload max size

projects/rero/ng-core/src/lib/validator/time.validator.ts
=> validators: fix custom validators return type

projects/rero/ng-core/src/lib/translate/i18n/fr.json, projects/rero/ng-core/src/lib/translate/i18n/it.json
French translated at 100.0% (81 of 81 strings)
Italian translated at 100.0% (81 of 81 strings)
Co-authored-by: Nicolas Prongué <n.prongue@outlook.com>
Translate-URL: https://hosted.weblate.org/projects/rero_plus/ng-core/
Translation: RERO+/ng-core
=> translations: update catalog

projects/rero/ng-core/src/lib/record/editor/widgets/dropdown-label-editor/dropdown-label-editor.component.html, projects/rero/ng-core/src/lib/record/editor/widgets/label/label.component.html
* Adds id html attributes on editor's clone and remove buttons.
To make Cypress tests cleaner.
My PR depends on the following PR(s):
* https://github.com/rero/rero-ils/pull/1595
Check id html attributes in template (clone and remove buttons).
=> tests: add id html attributes for cypress tests

projects/rero/ng-core/src/lib/record/detail/detail.component.ts
Allows to set an observable for the detail view configuration instead of specify directly the component class.
=> resources: observable for detail view

projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.component.ts, projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.service.ts, projects/rero/ng-core/src/lib/record/record.service.ts
* Improves typeahead by allowing suggestions based on ES suggestions completion.
=> records: typeahead suggestions

projects/ng-core-tester/src/app/app-routing.module.ts, projects/rero/ng-core/src/lib/record/record.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.ts
Adds support for custom search filters. This is represented by buttons above facets, which can turn on/off a filter value.
=> search: support for search filters

projects/rero/ng-core/ng-package.json
- Fix warning on build ng-core
=> dependencies: fix warning on build

projects/rero/ng-core/src/lib/record/editor/widgets/load-template-form/load-template-form.component.html, projects/rero/ng-core/src/lib/record/editor/widgets/load-template-form/load-template-form.component.ts
- Empty select on template form
- Check template dialog
=> template: display of the form after loading the data

projects/ng-core-tester/src/app/app-routing.module.ts, projects/rero/ng-core/src/lib/record/record.ts, projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.ts, projects/rero/ng-core/src/lib/record/search/record-search.service.ts
* Replaces the button by a toggle on the filter display.
* Adds URL parameters on searchFilter.
* Updates the routing configuration to show all options.
- Improve search filters to add some options
- Check configuration and test filters on `Backend` url
=> search: improve filter configuration

projects/rero/ng-core/src/lib/dialog/dialog.component.html, projects/rero/ng-core/src/lib/error/error.component.html, projects/rero/ng-core/src/lib/menu/menu-widget/menu-widget.component.html, projects/rero/ng-core/src/lib/record/autocomplete/autocomplete.component.html, projects/rero/ng-core/src/lib/record/detail/detail.component.html, projects/rero/ng-core/src/lib/record/editor/editor.component.html, projects/rero/ng-core/src/lib/record/editor/type/array-type/array-type.component.html, projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.html, projects/rero/ng-core/src/lib/record/editor/type/object-type/object-type.component.html, projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.component.html, projects/rero/ng-core/src/lib/record/editor/widgets/add-field-editor/add-field-editor.component.html, projects/rero/ng-core/src/lib/record/editor/widgets/dropdown-label-editor/dropdown-label-editor.component.html, projects/rero/ng-core/src/lib/record/editor/widgets/label/label.component.html, projects/rero/ng-core/src/lib/record/editor/widgets/load-template-form/load-template-form.component.html, projects/rero/ng-core/src/lib/record/editor/widgets/save-template-form/save-template-form.component.html, projects/rero/ng-core/src/lib/record/files/files.component.html, projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.html, projects/rero/ng-core/src/lib/record/search/aggregation/slider/slider.component.html, projects/rero/ng-core/src/lib/record/search/record-search-page.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/result/record-search-result.component.html, projects/rero/ng-core/src/lib/text-read-more/text-read-more.component.html, projects/rero/ng-core/src/lib/widget/menu/menu.component.html, projects/rero/ng-core/src/lib/widget/sort-list/sort-list.component.html
Fixes miscellaneous character into HTML copyright files.
=> General : fix HTML copyright

CHANGELOG.md, package-lock.json, package.json, projects/rero/ng-core/package.json
=> release: version 1.12.2

projects/ng-core-tester/src/app/app-routing.module.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.ts
Displays a message if no record is found for a resource type, instead
of displaying the search component.
=> records: display no record message

projects/ng-core-tester/src/app/routes/documents-route.ts, projects/ng-core-tester/src/app/routes/route.service.ts, projects/rero/ng-core/src/lib/record/record-ui.service.spec.ts, projects/rero/ng-core/src/lib/record/record-ui.service.ts
=> resources: customize the delete message

projects/rero/ng-core/src/lib/search-input/search-input.component.html, projects/rero/ng-core/src/lib/search-input/search-input.component.ts
=> search input: add the disabled attribute

projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.component.html
=> typeahead: allow html content

projects/rero/ng-core/src/lib/record/detail/detail.component.ts, projects/rero/ng-core/src/lib/record/record-ui.service.ts
* Adds new parameter action on redirectUrl function.
* Removes the redirection to the cancel action from the confirmation dialog.
=> configuration: add action parameter on redirectUrl

projects/rero/ng-core/src/lib/translate/i18n/de.json, projects/rero/ng-core/src/lib/translate/i18n/fr.json, projects/rero/ng-core/src/lib/translate/i18n/it.json
German currently translated at 100.0% (93 of 93 strings)
French currently translated at 100.0% (93 of 93 strings)
Italian currently translated at 100.0% (93 of 93 strings)
Translate-URL: https://hosted.weblate.org/projects/rero_plus/ng-core/de/
Translate-URL: https://hosted.weblate.org/projects/rero_plus/ng-core/fr/
Translate-URL: https://hosted.weblate.org/projects/rero_plus/ng-core/it/
Translation: RERO+/ng-core
Co-authored-by: Nicolas Prongué <n.prongue@outlook.com>
=> translations: translate v0.13.1

package-lock.json, package.json
=> dependencies: fix security issues

projects/ng-core-tester/src/app/app-routing.module.ts, projects/rero/ng-core/src/lib/record/search/record-search-page.component.spec.ts, projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.spec.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.ts
Enables sort options to sort records.
=> search: enable sort options

package-lock.json, package.json, projects/rero/ng-core/package.json
- Made an error during the package publishing.
=> release: version 1.14.1

CHANGELOG.md, package-lock.json, package.json, projects/rero/ng-core/package.json
=> release: version 1.14.3

CHANGELOG.md, package-lock.json, package.json, projects/rero/ng-core/package.json
Co-Authored-by: PascalRepond <pascal.repond@rero.ch>
=> release: version 1.14.4

CHANGELOG.md, package-lock.json, package.json, projects/rero/ng-core/package.json
=> release: version 1.14.5

.github_changelog_generator, CHANGELOG.md
=> documentation: add changelog generator default params

projects/rero/ng-core/src/lib/record/search/aggregation/date-range/date-range.component.html, projects/rero/ng-core/src/lib/record/search/aggregation/date-range/date-range.component.ts
* Removes some useless styling classNames.
* Fixes known date filters parameters.
=> facets: fix date range facet

projects/rero/ng-core/src/lib/record/export-button/export-button.component.html, projects/rero/ng-core/src/lib/record/export-button/export-button.component.spec.ts, projects/rero/ng-core/src/lib/record/export-button/export-button.component.ts, projects/rero/ng-core/src/lib/record/record.module.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.ts, projects/rero/ng-core/src/public-api.ts
* Adds export button component.
Co-Authored-by: Lauren-D <laurent.dubois@itld-solutions.be>
=> record: generalize export button

CHANGELOG.md, package-lock.json, package.json, projects/rero/ng-core/package.json
Co-Authored-by: Pascal Repond <pascal.repond@rero.ch>
=> release: v1.16.0

projects/rero/ng-core/src/lib/record/search/record-search.component.html
=> search filters: fix label translation

CHANGELOG.md, package-lock.json, package.json, projects/rero/ng-core/package.json
Co-Authored-by: Pascal Repond <pascal.repond@rero.ch>
=> release: v1.16.1

projects/rero/ng-core/src/lib/record/search/aggregation/list-filters/list-filters.component.ts
* Closes https://github.com/rero/rero-ils/issues/3094.
=> search filters: hide simple filter

projects/rero/ng-core/src/lib/record/search/aggregation/list-filters/list-filters.component.html
=> aggregation: add title to filter button

CHANGELOG.md, package-lock.json, package.json, projects/rero/ng-core/package.json
* Minor version to add missing translations.
=> release: v14.2.1

projects/rero/ng-core/src/lib/translate/date-translate-pipe.spec.ts, projects/rero/ng-core/src/lib/translate/date-translate-pipe.ts, projects/rero/ng-core/src/lib/translate/translate-service.ts
=> translate: change locale en by en-GB

package-lock.json, package.json, projects/rero/ng-core/package.json
=> release: v14.4.0

CHANGELOG.md, package-lock.json, package.json, projects/rero/ng-core/package.json
=> release: v14.5.0

projects/rero/ng-core/src/lib/record/editor/extensions.ts
=> formly: fix default value expression

projects/ng-core-tester/src/app/record/editor/schema.json, projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.html, projects/rero/ng-core/src/lib/record/editor/utils.spec.ts, projects/rero/ng-core/src/lib/record/editor/utils.ts
=> editor: fix resolve $ref definition on jsonschema

projects/rero/ng-core/src/lib/error/error.component.html, projects/rero/ng-core/src/lib/record/record.handle-error.service.ts, projects/rero/ng-core/src/lib/record/record.service.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.ts, projects/rero/ng-core/src/public-api.ts
* Adds a new service handle error.
* Updates record service with the new handle error.
=> chore: refactoring handle error

projects/ng-core-tester/src/app/record/editor/schema.json, projects/ng-core-tester/src/assets/i18n/de.json, projects/ng-core-tester/src/assets/i18n/fr.json, projects/ng-core-tester/src/assets/i18n/it.json, projects/rero/ng-core/src/lib/record/editor/extensions.ts
=> editor: fix addon right and left translation

projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.html, projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.ts
* Adds hideLabelSelectOption option for ngx-formly custom-select.
=> feat(editor): add option on custom-select

projects/rero/ng-core/src/lib/record/files/file/file.component.html, projects/rero/ng-core/src/lib/record/files/file/file.component.ts, projects/rero/ng-core/src/lib/record/files/files.component.html, projects/rero/ng-core/src/lib/record/files/files.component.ts, projects/rero/ng-core/src/lib/record/files/files.service.spec.ts, projects/rero/ng-core/src/lib/record/files/files.service.ts, projects/rero/ng-core/src/lib/record/record.module.ts, projects/rero/ng-core/src/lib/record/record.ts, projects/rero/ng-core/src/public-api.ts
* Refactors the file component and service.
=> files: add invenio record resources support

projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/editor/utils.ts, projects/rero/ng-core/src/lib/record/files/files.service.ts
* Fixes the recursive process of the initialRequired property.
* Optimizes the process of JSONSchema.
* Improves the error message on form.
=> fix(editor): process json schema

package-lock.json, projects/rero/ng-core/src/lib/record/editor/type/remote-typeahead/remote-typeahead.component.ts
* Fixes typeahead value deletion.
* Fixes refresh label value on typeahead after insert.
* Updates dependencies.
* Closes https://github.com/rero/rero-ils/issues/3661.
* Closes https://github.com/rero/rero-ils/issues/2625.
=> fix(editor): remote typeahead clear value

projects/rero/ng-core/src/lib/record/record-ui.service.ts
- Allows to navigate with a full URL after an edition or creation.
=> editor: add URL parameters support

projects/rero/ng-core/assets/scss/_theme.scss, projects/rero/ng-core/assets/scss/_typography.scss, projects/rero/ng-core/src/lib/dialog/dialog.component.ts, projects/rero/ng-core/src/lib/record/detail/detail-button/detail-button.component.html, projects/rero/ng-core/src/lib/record/editor/formly/primeng/remote-autocomplete/remote-autocomplete.ts, projects/rero/ng-core/src/lib/record/editor/type/array-type/array-type.component.html, projects/rero/ng-core/src/lib/record/editor/type/object-type/object-type.component.html, projects/rero/ng-core/src/lib/record/editor/type/switch/switch.component.ts, projects/rero/ng-core/src/lib/record/editor/widgets/add-field-editor/add-field-editor.component.ts, projects/rero/ng-core/src/lib/record/editor/wrappers/form-field-wrapper/form-field-wrapper.component.ts, projects/rero/ng-core/src/lib/record/record-ui.service.ts, projects/rero/ng-core/src/lib/record/search/aggregation/list-filters/list-filters.component.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.html, projects/rero/ng-core/src/lib/record/search/record-search.component.ts
* Fixes css styles.
* Adjusts some editor spaces.
* Fixes the editor switch component and removes the intermediate state as it is not used.
* Fixes agregations list filters translations.
=> primeng: fixe editor components

projects/rero/ng-core/assets/scss/_theme.scss, projects/rero/ng-core/src/lib/record/editor/services/jsonschema.service.ts, projects/rero/ng-core/src/lib/record/editor/wrappers/toggle-wrapper/toggle-wrappers.component.ts
* Fixes the default value for the array in the editor.
* Adds margins for dd dl.
=> primeng: toggle wrapper

projects/rero/ng-core/src/lib/record/editor/editor.component.html, projects/rero/ng-core/src/lib/record/editor/widgets/load-template-form/load-template-form.component.html, projects/rero/ng-core/src/lib/record/editor/widgets/load-template-form/load-template-form.component.ts
* Changes the position of the load template.
* Changes the label of submit button to load.
* Fixes translation of form buttons.
=> fix(templates): incorrect select display

projects/ng-core-tester/src/app/record/editor/schema.json, projects/rero/ng-core/src/lib/record/editor/editor.component.html, projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/editor/extensions.ts, projects/rero/ng-core/src/lib/record/editor/formly/primeng/date-picker/date-picker.ts, projects/rero/ng-core/src/lib/record/editor/formly/primeng/multi-select/multi-select.spec.ts, projects/rero/ng-core/src/lib/record/editor/formly/primeng/multi-select/multi-select.ts, projects/rero/ng-core/src/lib/record/editor/formly/primeng/select/select.spec.ts, projects/rero/ng-core/src/lib/record/editor/formly/primeng/select/select.ts, projects/rero/ng-core/src/lib/record/editor/formly/primeng/tree-select/tree-select.spec.ts, projects/rero/ng-core/src/lib/record/editor/formly/primeng/tree-select/tree-select.ts, projects/rero/ng-core/src/lib/record/record.handle-error.service.ts
=> editor: fix missing server error

projects/rero/ng-core/src/lib/record/editor/type/password-generator-type.component.ts
The width/height of the action buttons on the component password.
This makes it easier to click on the chosen action.
=> fix(editor): the size of the action buttons

projects/rero/ng-core/assets/scss/_theme.scss
* Linked to https://github.com/rero/rero-ils-ui/pull/1273
=> chore(theme): move tag link color to ng-core

projects/rero/ng-core/src/lib/record/editor/editor.component.ts
* Displayed the validation errors when the form is submited.
=> feat: display validation errors on submit

projects/ng-core-tester/src/app/record/editor/schema.json, projects/rero/ng-core/src/lib/record/editor/editor.component.html
=> fix: translate the title editor description.

projects/rero/ng-core/src/lib/record/editor/formly/primeng/select/select.ts, projects/rero/ng-core/src/lib/record/editor/widgets/load-template-form/load-template-form.component.ts
* Adds a filter to the template picker.
* Expands the scrollHeight of the dropdown.
=> feat(templates): enhance load template modal

projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/editor/widgets/load-template-form/load-template-form.component.ts
=> fix(editor): "my private templates" should be displayed first also for standard librarians

projects/rero/ng-core/src/lib/search-input/search-input.component.ts
=> fix(circulation): set autofocus after each circulation operation

projects/rero/ng-core/src/lib/record/editor/editor.component.ts, projects/rero/ng-core/src/lib/record/editor/services/jsonschema.service.ts, projects/rero/ng-core/src/lib/record/editor/utils.ts, projects/rero/ng-core/src/lib/record/search/record-search-page.component.ts, projects/rero/ng-core/src/lib/record/search/record-search.component.ts, projects/rero/ng-core/tsconfig.lib.json
* Updates primeng packages.
* Removes circular imports.
* Fixes tsconfig file for ES2020.
=> fix(search): fix query when using a search field

projects/rero/ng-core/src/lib/record/editor/formly/primeng/select/select.ts
Close https://github.com/rero/rero-ils/issues/3885.
=> fix(select): translate default placeholder
